(function(){
  'use strict';
  const rosterId=new URLSearchParams(location.search).get('roster');if(!rosterId)return;
  let record;try{record=(JSON.parse(localStorage.getItem('wh40k-rosters-v1'))||[]).find(item=>item?.id===rosterId);}catch{}
  if(!record){location.replace('../../roster-guides/index.html?missing='+encodeURIComponent(rosterId));return;}
  let roster=record.roster;if(record.sourceText&&window.WHRosterParser){const parsed=window.WHRosterParser.parse(record.sourceText);if(parsed.units.length)roster=parsed;}
  const normalize=value=>String(value||'').toLowerCase().replace(/\s*\[legends\]\s*$/i,'').replace(/[^a-z0-9]+/g,' ').trim(),slug=value=>normalize(value).replace(/\s+/g,'-');
  if(!['t au empire','tau empire'].includes(normalize(roster?.faction))||!roster?.units?.length){location.replace('../../roster-guides/index.html');return;}
  const cards=new Map([...document.querySelectorAll('.unit-card[data-unit-title]')].map(card=>[normalize(card.dataset.unitTitle),card])),selected=new Map();
  for(const unit of roster.units){const card=cards.get(normalize(unit.name));if(!card)continue;const entry=selected.get(card.id)||{card,units:[],points:0,loadout:[]};entry.units.push(unit);entry.points+=Number(unit.points)||0;entry.loadout.push(...[unit.wargear,...(unit.models||[]).flatMap(model=>[model.wargear,...(model.loadouts||[]).map(item=>item.wargear)])].filter(Boolean));selected.set(card.id,entry);}
  const labels=(roster.detachments?.length?roster.detachments.map(item=>item.label):[roster.detachment]).flatMap(value=>String(value||'').split(/\s*,\s*(?![^()]*\))/)).map(value=>value.replace(/\s*\([^)]*\)\s*$/,'')).filter(Boolean),detachmentIds=[...new Set(labels.map(slug))];
  const enhancementIds=new Map([...document.querySelectorAll('.enhancement[data-enhancement-title][data-rule-id]')].map(card=>[normalize(card.dataset.enhancementTitle),card.dataset.ruleId])),enhancementRuleIdsByUnitId={};
  for(const [cardId,entry] of selected){const owners=new Set(entry.units.map(unit=>unit.id));enhancementRuleIdsByUnitId[cardId]=[...new Set((roster.enhancements||[]).filter(item=>item.ownerStatus==='resolved'&&owners.has(item.ownerUnitId)).map(item=>enhancementIds.get(normalize(item.name))).filter(Boolean))];}
  window.TAU_ROSTER_GUIDE=Object.freeze({detachmentIds,enhancementRuleIdsByUnitId:Object.freeze(enhancementRuleIdsByUnitId)});
  document.title="T'au Empire Roster Guide";document.querySelector('.app-brand strong').textContent="T'au Empire Roster Guide";document.querySelector('[data-roster-guides]')?.removeAttribute('hidden');
  const hero=document.querySelector('#start');if(hero){hero.querySelector('.eyebrow').textContent='Personal roster guide';hero.querySelector('h1').textContent=record.name||"T'au Empire";hero.querySelector('h1 + p').textContent=`${roster.units.length} units · ${labels.join(' + ')}`;}
  document.querySelectorAll('.content-group.detachment').forEach(section=>{if(!detachmentIds.includes(section.id.replace(/^detachment-/,'')))section.remove();});document.querySelectorAll('[data-nav-id^="detachment-"]').forEach(item=>{if(item.dataset.navDepth==='2'&&!detachmentIds.includes(item.dataset.navId.replace(/^detachment-/,'')))item.remove();});
  document.querySelectorAll('.unit-card').forEach(card=>{const entry=selected.get(card.id);if(!entry){card.remove();return;}card.dataset.rosterSelected='true';const status=card.querySelector('.unit-status');if(status)status.textContent=`${entry.units.length>1?`${entry.units.length} units · `:''}${entry.points} pts`;const composition=card.querySelector('[id$="-composition"]');if(composition){const block=document.createElement('div');block.className='content-block roster-composition';const heading=document.createElement('strong');heading.textContent='Roster loadout';const list=document.createElement('ul');for(const item of entry.units){const row=document.createElement('li');row.textContent=`${item.quantity||1}× ${item.name}${item.wargear?` — ${item.wargear}`:''}`;list.append(row);}block.append(heading,list);composition.replaceChildren(composition.querySelector('h4'),block);}window.WHBookRosterEnhancements?.decorate(card,roster,entry.units);if(entry.loadout.length&&window.WHRosterEntities)card.querySelectorAll('.weapon-row:not(.weapon-head)').forEach(row=>{const label=row.querySelector('.weapon-button')?.textContent||row.firstElementChild?.textContent;if(label&&!window.WHRosterEntities.loadoutIncludesProfile(entry.loadout,label))row.remove();});card.querySelectorAll('.weapon-group').forEach(group=>{if(!group.querySelector('.weapon-row:not(.weapon-head)'))group.remove();});});
  document.querySelectorAll('[data-nav-id^="unit-"]').forEach(item=>{if(!selected.has(item.dataset.navId))item.remove();});document.querySelectorAll('#datasheets > .content-group').forEach(group=>{if(!group.querySelector('.unit-card')){document.querySelector(`[data-nav-id="${CSS.escape(group.id)}"]`)?.remove();group.remove();}});
}());
