(function(root){
  'use strict';
  const SCHEMA='wh40k-army-roster-context/v1',CATALOG_SCHEMA='wh40k-army-roster-catalog/v1',GAME_SCHEMA='wh40k-physical-unit-game-projection/v1',STORAGE_KEY='wh40k-rosters-v1',UNKNOWN='unknown';
  const normalize=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),list=value=>Array.isArray(value)?value:[],unique=values=>[...new Set(values.filter(Boolean))],frozen=value=>Object.freeze(value),freezeList=value=>frozen(list(value).map(item=>item&&typeof item==='object'?frozen(item):item));
  const keywordProfile=value=>{const source=value||{},intrinsic=unique(list(source.intrinsic)),added=unique(list(source.added)),removed=unique(list(source.removed)),removedKeys=new Set(removed.map(normalize)),hasEffective=Object.prototype.hasOwnProperty.call(source,'effective'),explicitState=String(source.state||'').trim(),effective=hasEffective?unique(list(source.effective)):explicitState&&explicitState!==UNKNOWN?unique([...intrinsic,...added]).filter(item=>!removedKeys.has(normalize(item))):[],state=explicitState||(hasEffective||intrinsic.length||added.length||removed.length?'known':UNKNOWN);return frozen({intrinsic:freezeList(intrinsic),added:freezeList(added),removed:freezeList(removed),effective:freezeList(effective),state});};
  const unitRecord=unit=>{const keywords=keywordProfile(unit.keywordProfile||unit.keywords),instanceId=scalar(unit.instanceId??unit.id),datasheetId=scalar(unit.datasheetId??unit.canonicalDatasheetId??unit.canonicalUnitId),sourceBookId=scalar(unit.source?.bookId??unit.sourceBookId);return frozen({instanceId,instanceState:scalar(unit.instanceState)||(instanceId?'exact':UNKNOWN),datasheetId,datasheetState:scalar(unit.datasheetState)||(datasheetId?'exact':UNKNOWN),canonicalUnitId:datasheetId,canonicalDatasheetId:datasheetId,title:scalar(unit.title),sourceBookId:sourceBookId||'',source:frozen({bookId:sourceBookId,state:scalar(unit.source?.state??unit.sourceState)||(sourceBookId?'known':UNKNOWN),provenance:scalar(unit.source?.provenance??unit.sourceProvenance)}),supplementParent:unit.supplementParent||null,keywords,keywordProfile:keywords,enhancements:freezeList(unit.enhancements),attachments:freezeList(unit.attachments),group:unit.group?frozen({...unit.group}):null,formation:unit.formation?frozen({...unit.formation}):null,provenance:frozen({...unit.provenance})});};
  const relationGroup=value=>{if(!value)return frozen({state:UNKNOWN,entries:freezeList([])});const source=Array.isArray(value)?{entries:value}:value,entries=list(source.entries).map(entry=>frozen({id:scalar(entry.id),anchorInstanceId:scalar(entry.anchorInstanceId??entry.bodyguardInstanceId),memberInstanceIds:freezeList(unique(list(entry.memberInstanceIds??entry.characterInstanceIds))),instanceIds:freezeList(unique(list(entry.instanceIds))),state:scalar(entry.state)||scalar(source.state)||UNKNOWN,certainty:scalar(entry.certainty)||UNKNOWN,provenance:scalar(entry.provenance)||scalar(source.provenance)}));return frozen({state:scalar(source.state)||(entries.length?'known':UNKNOWN),entries:freezeList(entries)});},relationsProjection=value=>frozen({attachments:relationGroup(value?.attachments),groups:relationGroup(value?.groups),formations:relationGroup(value?.formations)});
  const scalar=value=>value==null||String(value).trim()===''?null:String(value).trim(),bookRecord=input=>{const source=input.book||{},id=scalar(source.id??input.bookId),factionId=scalar(source.factionId??input.factionId??input.bookId),parentBookId=scalar(source.parentBookId??input.parentBookId);return frozen({id,factionId,parentBookId,state:scalar(source.state)||(id?'known':'unknown')});};
  const enhancementRecord=enhancement=>{const instanceId=enhancement.owner?.instanceId??enhancement.ownerInstanceId??enhancement.ownerUnitId??null;return frozen({...enhancement,owner:frozen({...enhancement.owner,instanceId:instanceId==null?null:String(instanceId),state:enhancement.owner?.state??enhancement.ownerState??enhancement.ownerStatus??(instanceId==null?'unknown':'resolved')})});};
  function create(input={}){return frozen({schema:SCHEMA,status:scalar(input.status)||UNKNOWN,book:bookRecord(input),bookId:String(input.bookId||input.book?.id||''),factionId:String(input.factionId||input.book?.factionId||input.bookId||input.book?.id||''),parentBookId:input.parentBookId??input.book?.parentBookId??null,rosterId:scalar(input.rosterId),detachment:input.detachment?frozen({...input.detachment}):null,detachments:freezeList(input.detachments),enhancements:freezeList(list(input.enhancements).map(enhancementRecord)),units:freezeList(list(input.units).map(unitRecord)),relations:relationsProjection(input.relations),attachments:freezeList(input.attachments),groups:freezeList(input.groups),formations:freezeList(input.formations),provenance:frozen({...input.provenance,kind:'runtime-projection',persistenceKey:STORAGE_KEY,persistedSchemaChanged:false})});}
  const indexCatalog=catalog=>{if(!catalog||catalog.schema!==CATALOG_SCHEMA)throw new Error('Canonical roster catalog is unavailable or invalid');const unitsById=new Map(list(catalog.units).map(unit=>[unit.id,unit])),unitsByTitle=new Map(list(catalog.units).map(unit=>[normalize(unit.title),unit])),detachmentsById=new Map(list(catalog.detachments).map(item=>[item.id,item])),detachmentsByTitle=new Map(list(catalog.detachments).map(item=>[normalize(item.title),item])),detachmentRulesById=new Map(),enhancementsById=new Map(),enhancementsByTitle=new Map(),abilitiesById=new Map();for(const rule of list(catalog.detachmentRules))for(const id of [rule.id,rule.sectionId].filter(Boolean))detachmentRulesById.set(normalize(id),rule);for(const unit of list(catalog.units))for(const ability of [...list(unit.gameSelections?.abilities),...list(unit.gameSelections?.wargearAbilities)])for(const id of [ability.id,ability.sectionId].filter(Boolean))abilitiesById.set(normalize(id),ability);for(const item of list(catalog.enhancements)){for(const id of [item.id,item.ruleId,item.sourceId,item.legacyKey].filter(Boolean))enhancementsById.set(normalize(id),item);const key=normalize(item.title),items=enhancementsByTitle.get(key)||[];items.push(item);enhancementsByTitle.set(key,items);}return {unitsById,unitsByTitle,detachmentsById,detachmentsByTitle,detachmentRulesById,enhancementsById,enhancementsByTitle,abilitiesById};};
  const attachmentCanonical=value=>value?.canonicalUnit||value?.unit||value||null,attachmentInstanceId=value=>scalar(value?.instanceId??value?.id),attachmentUnitId=value=>scalar(attachmentCanonical(value)?.id??attachmentCanonical(value)?.unitId);
  const attachmentRelation=(bodyguardValue,leaderValue)=>{const bodyguard=attachmentCanonical(bodyguardValue),leader=attachmentCanonical(leaderValue),bodyguardId=attachmentUnitId(bodyguard),leaderId=attachmentUnitId(leader);if(!bodyguardId||!leaderId)return null;const find=(owner,key,targetId,kind)=>{const record=list(owner?.relations?.[key]).find(item=>scalar(item?.unitId??item?.id??item)===targetId);return record?frozen({...record,kind}):null;};return find(leader,'canLead',bodyguardId,'leader')||find(leader,'canSupport',bodyguardId,'support')||find(bodyguard,'canBeLedBy',leaderId,'leader')||find(bodyguard,'canBeSupportedBy',leaderId,'support')||null;};
  const attachmentSupport=(bodyguardValue,leaderValue)=>{const bodyguard=attachmentCanonical(bodyguardValue),leader=attachmentCanonical(leaderValue),bodyguardId=attachmentUnitId(bodyguard),leaderId=attachmentUnitId(leader);return Boolean(list(leader?.relations?.canSupport).some(item=>scalar(item?.unitId??item?.id??item)===bodyguardId)||list(bodyguard?.relations?.canBeSupportedBy).some(item=>scalar(item?.unitId??item?.id??item)===leaderId));};
  const attachmentUnits=value=>list(value).map(item=>({instanceId:attachmentInstanceId(item),canonicalUnit:attachmentCanonical(item)})).filter(item=>item.instanceId&&attachmentUnitId(item.canonicalUnit));
  const attachmentGroupIssue=(bodyguard,leaders)=>{if(!bodyguard)return 'missing-bodyguard';const canonicalIds=new Set(),relations=[];for(const leader of leaders){if(!leader)return 'missing-leader';if(leader.instanceId===bodyguard.instanceId)return 'same-physical-instance';const relation=attachmentRelation(bodyguard,leader);if(!relation)return 'pair-not-canonical';const canonicalId=attachmentUnitId(leader);if(canonicalIds.has(canonicalId))return 'duplicate-canonical-leader';canonicalIds.add(canonicalId);relations.push(relation);}const limit=relations.length?Math.min(...relations.map(item=>Math.max(1,Number(item.maxCharacters)||1))):1;if(leaders.length>limit)return 'max-characters';if(leaders.length>1&&!leaders.some(item=>attachmentSupport(bodyguard,item)))return 'support-required';return '';};
  const freezeAttachments=value=>frozen(Object.fromEntries(Object.entries(value).map(([id,ids])=>[id,freezeList(ids)])));
  const sanitizeAttachments=(input={})=>{const units=attachmentUnits(input.units),byInstance=new Map(units.map(item=>[item.instanceId,item])),attachments={},rejected=[],used=new Set();for(const [bodyguardId,leaderRefs] of Object.entries(input.attachments||{})){const bodyguard=byInstance.get(bodyguardId),accepted=[];if(!bodyguard){for(const reference of list(leaderRefs))rejected.push({bodyguardInstanceId:bodyguardId,leaderInstanceId:scalar(typeof reference==='string'?reference:reference?.unitId??reference?.instanceId),reason:'missing-bodyguard'});continue;}for(const reference of list(leaderRefs)){const leaderId=scalar(typeof reference==='string'?reference:reference?.unitId??reference?.instanceId),leader=byInstance.get(leaderId);let reason=!leader?'missing-leader':used.has(leaderId)?'leader-already-attached':accepted.some(item=>item.instanceId===leaderId)?'duplicate-physical-leader':attachmentGroupIssue(bodyguard,[...accepted,leader]);if(reason){rejected.push({bodyguardInstanceId:bodyguardId,leaderInstanceId:leaderId,reason});continue;}accepted.push(leader);used.add(leaderId);}if(accepted.length)attachments[bodyguardId]=accepted.map(item=>item.instanceId);}return frozen({attachments:freezeAttachments(attachments),rejected:freezeList(rejected)});};
  const attachmentCandidates=(input={})=>{const units=attachmentUnits(input.units),state=sanitizeAttachments({...input,units}),bodyguard=units.find(item=>item.instanceId===input.bodyguardInstanceId);if(!bodyguard)return freezeList([]);const currentIds=list(state.attachments[bodyguard.instanceId]),current=currentIds.map(id=>units.find(item=>item.instanceId===id)).filter(Boolean),used=new Set(Object.entries(state.attachments).filter(([id])=>id!==bodyguard.instanceId).flatMap(([,ids])=>ids));return freezeList(units.filter(item=>item.instanceId!==bodyguard.instanceId&&!currentIds.includes(item.instanceId)&&!used.has(item.instanceId)&&!attachmentGroupIssue(bodyguard,[...current,item])));};
  const attachExplicit=(input={})=>{const state=sanitizeAttachments(input),bodyguardId=scalar(input.bodyguardInstanceId),leaderId=scalar(input.leaderInstanceId),current=list(state.attachments[bodyguardId]);if(!bodyguardId||!leaderId||current.includes(leaderId))return frozen({...state,changed:false});const next={...state.attachments,[bodyguardId]:[...current,leaderId]},validated=sanitizeAttachments({...input,attachments:next}),changed=list(validated.attachments[bodyguardId]).includes(leaderId);return frozen({...validated,changed});};
  const detachExplicit=(input={})=>{const state=sanitizeAttachments(input),bodyguardId=scalar(input.bodyguardInstanceId),leaderId=scalar(input.leaderInstanceId),current=list(state.attachments[bodyguardId]),nextIds=current.filter(id=>id!==leaderId),next={...state.attachments};if(nextIds.length)next[bodyguardId]=nextIds;else delete next[bodyguardId];const validated=sanitizeAttachments({...input,attachments:next});return frozen({...validated,changed:current.length!==nextIds.length});};
  const attachmentWorkflow=frozen({relation:attachmentRelation,support:attachmentSupport,sanitize:sanitizeAttachments,candidates:attachmentCandidates,attach:attachExplicit,detach:detachExplicit});
  const runtimeInput=(options={})=>{if(options.roster)return {roster:options.roster,record:options.record||{},rosterId:options.rosterId||options.record?.id||null};const location=options.location||root.location,storage=options.storage||root.localStorage,rosterId=new URLSearchParams(location?.search||'').get('roster');if(!rosterId||!storage)return {roster:null,record:null,rosterId:null};let records=[];try{records=JSON.parse(storage.getItem('wh40k-rosters-v1')||'[]');}catch{}const record=list(records).find(item=>item?.id===rosterId)||null;if(!record)return {roster:null,record:null,rosterId};const parsed=record.sourceText&&root.WHRosterParser?.parse?root.WHRosterParser.parse(record.sourceText):null;return {roster:parsed?.units?.length?parsed:record.roster||null,record,rosterId};};
  const explicitFor=(source,instanceId)=>{if(!source)return [];if(Array.isArray(source))return source.filter(item=>item?.unitId===instanceId||item?.instanceId===instanceId||item?.sourceId===instanceId);return list(source[instanceId]);};
  const resolveDetachment=(raw,index)=>index.detachmentsById.get(raw?.id)||index.detachmentsByTitle.get(normalize(raw?.name||raw?.label||raw))||null;
  const resolveEnhancement=(raw,index,detachmentIds)=>{const byId=index.enhancementsById.get(normalize(raw?.ruleId||raw?.id));if(byId)return byId;const candidates=index.enhancementsByTitle.get(normalize(raw?.name||raw?.title))||[];return candidates.find(item=>!item.detachmentId||detachmentIds.has(item.detachmentId))||candidates[0]||null;};
  const grantKeywords=(unit,detachments)=>{const added=[];for(const detachment of detachments)for(const grant of list(detachment.keywordGrants)){const ids=list(grant.unitIds||grant.units),titles=list(grant.unitTitles||grant.titles).map(normalize);if((!ids.length&&!titles.length)||ids.includes(unit.id)||titles.includes(normalize(unit.title)))added.push(...list(grant.add||grant.keywords),...(grant.keyword?[grant.keyword]:[]));}return added;};
  const identityParts=value=>unique(String(value||'').split(/\s+-\s+/).map(normalize));
  const rosterCompatibility=(roster,catalog)=>{const rosterIdentities=identityParts(roster?.faction??roster?.factionId),book=catalog.book||{},catalogIdentities=unique([book.id,book.title,book.factionKeyword,book.parentBookId,...list(book.dependencies).flatMap(item=>[item?.bookId,item?.id,item?.title])].flatMap(identityParts));return frozen({state:!rosterIdentities.length?'unknown':rosterIdentities.some(identity=>catalogIdentities.includes(identity))?'compatible':'incompatible',rosterIdentities:freezeList(rosterIdentities),catalogIdentities:freezeList(catalogIdentities)});};
  const splitSelections=value=>{const output=[];let depth=0,start=0,text=String(value||'');for(let index=0;index<text.length;index++){if(text[index]==='(')depth++;else if(text[index]===')')depth=Math.max(0,depth-1);else if(text[index]===','&&depth===0){output.push(text.slice(start,index));start=index+1;}}output.push(text.slice(start));return output.map(item=>item.trim()).filter(Boolean);};
  const selectionParts=value=>{const sourceText=String(value||'').trim(),match=sourceText.match(/^\s*(\d+)\s*[x\u00d7]\s*/i),quantity=match?Number(match[1]):1;return {sourceText,matchText:(match?sourceText.slice(match[0].length):sourceText).trim(),quantity};};
  const selectionInputs=raw=>{const rows=[];const add=(value,modelQuantity,model)=>{for(const valueText of splitSelections(value)){const selection=selectionParts(valueText),models=Number(modelQuantity);rows.push({...selection,modelQuantity:Number.isFinite(models)?models:null,totalQuantity:Number.isFinite(models)?selection.quantity*models:null,model:model||null});}};if(list(raw?.models).length)for(const model of raw.models){if(list(model.loadouts).length)for(const loadout of model.loadouts)add(loadout.wargear,loadout.quantity??model.quantity,model.name);else add(model.wargear,model.quantity,model.name);}else add(raw?.wargear,raw?.quantity,raw?.name);return rows;};
  const resolvedValue=(value,state,provenance)=>frozen({value,state,provenance:frozen(provenance)});
  const resolveGameSelection=(input,metadata)=>{const candidates=list(metadata?.selections).filter(selection=>unique([selection.title,...list(selection.aliases)]).some(alias=>normalize(alias)===normalize(input.matchText))),candidateKinds=unique(candidates.map(selection=>selection.kind||'wargear')),kind=candidateKinds.length===1?candidateKinds[0]:'unknown';if(candidates.length!==1)return frozen({...input,kind,state:candidates.length?'ambiguous':'unresolved',reason:candidates.length?'multiple-selection-candidates':'no-canonical-alias',candidateIds:freezeList(candidates.map(item=>item.id)),profileIds:freezeList([]),wargearAbilityIds:freezeList([])});const selection=candidates[0],missingAbility=list(selection.candidateWargearAbilityIds).length&&!list(selection.wargearAbilityIds).length;return frozen({...input,selectionId:selection.id,canonicalTitle:selection.title,kind:selection.kind||'wargear',profileIds:freezeList(selection.profileIds),wargearAbilityIds:freezeList(selection.wargearAbilityIds),state:missingAbility?'unresolved':'resolved',reason:missingAbility?'missing-wargear-ability-link':null,candidateIds:freezeList(missingAbility?selection.candidateWargearAbilityIds:[]),provenance:frozen({kind:'canonical-roster-selection',catalogSchema:CATALOG_SCHEMA})});};
  const adjusted=(value,delta)=>{const text=String(value??'').trim(),amount=Number(delta);if(!Number.isInteger(amount))return null;const dice=text.match(/^(\d*[dD]\d+)(?:\s*([+-])\s*(\d+))?$/);if(dice){const modifier=(dice[2]==='-'?-1:1)*Number(dice[3]||0)+amount;return`${dice[1]}${modifier===0?'':modifier>0?`+${modifier}`:modifier}`;}const match=text.match(/^(-?\d+)(.*)$/);if(!match)return null;return`${Number(match[1])+amount}${match[2]}`;};
  const effectActive=effect=>(effect.state||'active')==='active'&&(effect.certainty||'current')==='current'&&effect.condition?.state!=='unknown';
  const statBase=(metadata,id)=>{const entry=Object.entries(metadata?.stats||{}).find(([key])=>normalize(key)===normalize(id));return entry?String(entry[1]??''):null;};
  const canonicalProfile=profile=>{const mode=String(profile.mode||profile.type||'').toLowerCase().startsWith('melee')?'melee':'ranged',values=profile.characteristics||{};return {id:profile.id||'',title:profile.title||profile.name||'',mode,values:{Range:values.Range??profile.range??'',A:values.A??profile.a??'',[mode==='melee'?'WS':'BS']:values[mode==='melee'?'WS':'BS']??profile.skill??'',S:values.S??profile.s??'',AP:values.AP??profile.ap??'',D:values.D??profile.d??''},tags:unique(String(values.Keywords??profile.abilities??'').split(',').map(value=>value.trim()))};};
  const profileMatches=(profile,effect,selectedIds,selectedResolved)=>{const target=String(effect.targetId||'all'),selected=selectedResolved&&selectedIds.has(profile.id);if(!selected)return false;if(target==='all')return true;if(target==='ranged'||target==='melee')return profile.mode===target;if(target==='selected-melee')return profile.mode==='melee'&&(!list(effect.profileIds).length||effect.profileIds.includes(profile.id));if(target==='psychic')return profile.tags.some(tag=>normalize(tag)==='psychic');if(target.startsWith('tag:'))return profile.tags.some(tag=>normalize(tag)===normalize(target.slice(4)));if(target==='plasma')return normalize(profile.title).includes('plasma');if(target.startsWith('family:'))return normalize(profile.title).startsWith(normalize(target.slice(7)));return target===profile.id;};
  const reduceGameEffects=(effects,draft,index)=>{const metadata=draft.item.catalogUnit.gameSelections||{},stats=new Map(Object.entries(metadata.stats||{}).map(([key,value])=>[key,String(value??'')])),profiles=new Map(list(metadata.weaponProfiles).map(profile=>{const record=canonicalProfile(profile);return[record.id,record];})),selectedIds=new Set(list(draft.selection.loadout.selectedProfileIds)),selectedResolved=draft.selection.loadout.weaponResolution?.state==='resolved'&&selectedIds.size>0,targetState=selectedResolved?'resolved':'unresolved',keywordState=new Set(list(draft.rosterState.keywordProfile.effective)),abilityState=new Map(list(metadata.abilities).map(ability=>[ability.id||normalize(ability.title),{...ability,canonical:true}])),records=[];
    for(const raw of effects){const effect={...raw,targetInstanceId:raw.targetInstanceId||draft.identity.instanceId,state:raw.state||'active',certainty:raw.certainty||'current'},active=effectActive(effect),targets=[];if(effect.targetInstanceId!==draft.identity.instanceId)continue;
      if(effect.component==='stat'){const current=[...stats.entries()].find(([key])=>normalize(key)===normalize(effect.targetId)),base=current?.[1]??statBase(metadata,effect.targetId),next=active?(effect.operation==='set'?String(effect.to):adjusted(base,effect.delta)):base;if(base!=null&&next!=null){if(active)stats.set(current?.[0]||effect.targetId,next);effect.base=base;effect.effective=next;}}
      else if(effect.component==='weapon'&&effect.operation==='grant-profile'){const profile=effect.profile?canonicalProfile({...effect.profile,id:effect.profile.id||`${effect.id}-profile`}):null;if(profile&&active){profiles.set(profile.id,profile);targets.push({profileId:profile.id,operation:'grant-profile',effective:{...profile}});}effect.targetState=profile?'resolved':'unresolved';}
      else if(effect.component==='weapon'){for(const profile of profiles.values()){if(!profileMatches(profile,effect,selectedIds,selectedResolved))continue;if(effect.operation==='grant-tag'){const before=[...profile.tags],alreadyPresent=before.some(tag=>normalize(tag)===normalize(effect.tag)),after=active&&!alreadyPresent?[...before,effect.tag]:before;if(active)profile.tags=after;if(JSON.stringify(before)!==JSON.stringify(after))targets.push({profileId:profile.id,field:'Keywords',base:before,effective:after});}else if(effect.operation==='add-stat'||effect.operation==='set-stat'){const field=effect.stat,base=profile.values[field],next=active?(effect.operation==='set-stat'?String(effect.to):adjusted(base,effect.delta)):base;if(base!=null&&next!=null){if(active)profile.values[field]=next;targets.push({profileId:profile.id,field,base,effective:next});}}}effect.targetState=targetState;}
      else if(effect.component==='ability'){if(effect.operation==='reference'){const requested=effect.canonicalReference?.kind&&effect.canonicalReference?.id?effect.canonicalReference:effect.canonicalAbilityId?{kind:'ability',id:effect.canonicalAbilityId}:null,kind=requested?.kind==='enhancement'?'enhancement':requested?.kind==='detachment-rule'?'detachment-rule':'ability',source=requested?(kind==='enhancement'?index?.enhancementsById.get(normalize(requested.id)):kind==='detachment-rule'?index?.detachmentRulesById.get(normalize(requested.id)):index?.abilitiesById.get(normalize(requested.id))):null,reference=source?{kind,id:source.id||requested.id,title:kind==='enhancement'?String(source.title||'').replace(/\s+-\s+\d+\s*pts$/i,'').trim():source.title,text:source.text||source.full||source.short||'',sectionId:source.sectionId||source.sourceId||source.id||requested.id}:null;effect.canonicalReference=reference;effect.canonicalAbility=reference?.kind==='ability'?{...reference}:null;effect.targetState=reference?'resolved':'unresolved';effect.base=false;effect.effective=false;}else{const key=effect.targetId||effect.id,existing=abilityState.get(key)||[...abilityState.values()].find(ability=>normalize(ability.title)===normalize(effect.title)),base=Boolean(existing);if(active){if(effect.operation==='remove'){if(existing)abilityState.delete(existing.id||normalize(existing.title));}else abilityState.set(key,{id:key,title:effect.title||key,summary:effect.summary||'',sourceEffectId:effect.id,canonical:false});}effect.base=base;effect.effective=effect.operation==='remove'?active?false:base:true;}}
      else if(effect.component==='keyword'){const key=effect.targetId,base=[...keywordState].some(value=>normalize(value)===normalize(key));if(active){if(effect.operation==='remove'){for(const value of [...keywordState])if(normalize(value)===normalize(key))keywordState.delete(value);}else keywordState.add(key);}effect.base=base;effect.effective=[...keywordState].some(value=>normalize(value)===normalize(key));}
      effect.targets=targets;records.push(effect);
    }
    return {effects:records,effective:{stats:Object.fromEntries(stats),weaponProfiles:[...profiles.values()],abilities:[...abilityState.values()],keywords:[...keywordState],state:records.some(effect=>effect.state==='conditional')?'conditional':'resolved'}};
  };
  const freezeEffect=(effect,instanceId)=>frozen({...effect,targetInstanceId:effect.targetInstanceId||instanceId,state:effect.state||'active',certainty:effect.certainty||'current',source:frozen({...effect.source}),condition:effect.condition?frozen({...effect.condition}):null,canonicalReference:effect.canonicalReference?frozen({...effect.canonicalReference}):null,canonicalAbility:effect.canonicalAbility?frozen({...effect.canonicalAbility}):null,targets:freezeList(list(effect.targets).map(target=>frozen({...target,base:Array.isArray(target.base)?freezeList(target.base):target.base,effective:target.effective&&typeof target.effective==='object'&&!Array.isArray(target.effective)?frozen({...target.effective}):Array.isArray(target.effective)?freezeList(target.effective):target.effective}))),provenance:frozen({kind:'curated-provider',...effect.provenance})});
  const freezeEffective=value=>frozen({stats:frozen({...value.stats}),weaponProfiles:freezeList(list(value.weaponProfiles).map(profile=>frozen({...profile,values:frozen({...profile.values}),tags:freezeList(profile.tags)}))),abilities:freezeList(list(value.abilities).map(ability=>frozen({...ability}))),keywords:freezeList(value.keywords),state:value.state||'resolved'});
  const selectionResolution=(resolved,kind)=>{const selected=resolved.filter(item=>item.kind===kind&&item.state==='resolved'),unresolved=resolved.filter(item=>item.kind===kind&&item.state!=='resolved'),unknown=resolved.filter(item=>item.kind==='unknown'&&item.state!=='resolved');let state;if(unresolved.length)state=selected.length?'partial':'unresolved';else if(unknown.length)state=selected.length?'partial':'unresolved';else if(selected.length)state='resolved';else state=resolved.length?'known-none':'not-provided';return frozen({state,unresolved:freezeList([...unresolved,...unknown])});};
  const gameProjection=({catalog,record,projectionUnits,detachments,enhancements,provider,roster,index})=>{
    const drafts=projectionUnits.map(item=>{
      const raw=item.raw,metadata=item.catalogUnit.gameSelections||{},models=list(raw.models),validModels=models.length>0&&models.every(model=>Number.isFinite(Number(model.quantity))&&Number(model.quantity)>=0),rawQuantity=Number(raw.quantity),validRawQuantity=Number.isInteger(rawQuantity)&&rawQuantity>0,canonicalModels=list(metadata.models).filter(model=>scalar(model?.id)&&scalar(model?.title)),singleCanonicalModel=canonicalModels.length===1&&!/^\d+\s*[-–]\s*\d+\s+/.test(canonicalModels[0].title)?canonicalModels[0]:null,derivedModels=!models.length&&validRawQuantity&&singleCanonicalModel?[frozen({canonicalModelId:singleCanonicalModel.id,sourceText:singleCanonicalModel.title,quantity:rawQuantity,state:'resolved',provenance:frozen({kind:'canonical-single-model-identity'})})]:[],compositionModels=validModels?models.map(model=>frozen({sourceText:model.name||'',quantity:Number(model.quantity)||0,state:'resolved'})):derivedModels,modelCount=validModels?models.reduce((sum,model)=>sum+Number(model.quantity),0):!models.length&&validRawQuantity?rawQuantity:null,modelCountState=validModels||(!models.length&&validRawQuantity)?'resolved':models.length?'unresolved':'not-provided',compositionState=validModels?'resolved':models.length?'unresolved':validRawQuantity?derivedModels.length?'resolved':'partial':'not-provided',compositionUnresolved=compositionState==='partial'?[frozen({kind:'model-breakdown',reason:canonicalModels.length?'ambiguous-canonical-model-identities':'missing-canonical-model-identity',sourceText:raw.name||raw.title||''})]:[],inputs=selectionInputs(raw),resolved=inputs.map(input=>resolveGameSelection(input,metadata)),resolvedWeapons=resolved.filter(item=>item.state==='resolved'&&item.kind==='weapon'),selectedProfileIds=unique(resolvedWeapons.flatMap(item=>list(item.profileIds))),selectedProfiles=resolvedWeapons.flatMap(item=>list(item.profileIds).map(profileId=>frozen({profileId,selectionId:item.selectionId,sourceText:item.sourceText,model:item.model,quantity:item.quantity,modelQuantity:item.modelQuantity,totalQuantity:item.totalQuantity}))),selectedWargearAbilityIds=unique(resolved.flatMap(item=>item.state==='resolved'?list(item.wargearAbilityIds):[])),unresolved=resolved.filter(item=>item.state!=='resolved'),selectionState=!inputs.length?'not-provided':unresolved.length===inputs.length?'unresolved':unresolved.length?'partial':'resolved';
      return {item,identity:{instanceId:raw.id,canonicalDatasheetId:item.catalogUnit.id,canonicalTitle:item.catalogUnit.title,sourceBookId:item.context.sourceBookId,supplementParent:item.context.supplementParent,state:'resolved'},selection:{modelCount:resolvedValue(modelCount,modelCountState,{kind:validModels?'parsed-roster-models':validRawQuantity?'parsed-roster-unit-quantity':'parsed-roster-models',sourceRef:raw.sourceRef||''}),points:resolvedValue(Number.isFinite(Number(raw.points))?Number(raw.points):null,Number.isFinite(Number(raw.points))?'resolved':'not-provided',{kind:'parsed-roster-unit',sourceRef:raw.sourceRef||''}),composition:{state:compositionState,models:compositionModels,unresolved:freezeList(compositionUnresolved)},loadout:{state:selectionState,weapons:freezeList(resolved.filter(item=>item.kind==='weapon')),wargear:freezeList(resolved.filter(item=>item.kind==='wargear')),unknown:freezeList(resolved.filter(item=>item.kind==='unknown')),weaponResolution:selectionResolution(resolved,'weapon'),wargearResolution:selectionResolution(resolved,'wargear'),selectedProfileIds:freezeList(selectedProfileIds),selectedProfiles:freezeList(selectedProfiles),selectedWargearAbilityIds:freezeList(selectedWargearAbilityIds),unresolved:freezeList(unresolved)}},rosterState:{detachments:freezeList(detachments.map(item=>item.id)),enhancements:freezeList(item.context.enhancements),keywordProfile:item.context.keywordProfile},attachments:{leaders:[],leading:[]},effects:[]};
    });
    const byInstance=new Map(drafts.map(draft=>[draft.identity.instanceId,draft]));
    const relation=(direction,other,bodyguardInstanceId,leaderInstanceId)=>frozen({direction,instanceId:other.identity.instanceId,canonicalUnitId:other.identity.canonicalDatasheetId,certainty:'current',provenance:frozen({kind:'explicit-roster-attachment',persistenceKey:STORAGE_KEY,bodyguardInstanceId,leaderInstanceId})});
    for(const [bodyguardId,leaderIds] of Object.entries(record.attachments||{})){const bodyguard=byInstance.get(bodyguardId);if(!bodyguard)continue;for(const leaderId of list(leaderIds)){const leader=byInstance.get(typeof leaderId==='string'?leaderId:leaderId?.unitId||leaderId?.instanceId);if(!leader)continue;bodyguard.attachments.leaders.push(relation('leader',leader,bodyguardId,leader.identity.instanceId));leader.attachments.leading.push(relation('leading',bodyguard,bodyguardId,leader.identity.instanceId));}}
    const shared={catalog,index,roster,record,detachments,enhancements,units:projectionUnits,gameUnits:drafts,byInstance};
    for(const draft of drafts){const reduced=reduceGameEffects(list(provider?.gameEffects?.({...shared,item:draft.item,gameUnit:draft})||[]),draft,index);draft.effects=reduced.effects.map(effect=>freezeEffect(effect,draft.identity.instanceId));draft.effective=freezeEffective(reduced.effective);}
    const units=drafts.map(draft=>{const output=frozen({identity:frozen(draft.identity),selection:frozen({...draft.selection,composition:frozen({...draft.selection.composition,models:freezeList(draft.selection.composition.models)}),loadout:frozen(draft.selection.loadout)}),rosterState:frozen(draft.rosterState),attachments:frozen({leaders:freezeList(draft.attachments.leaders),leading:freezeList(draft.attachments.leading)}),effects:freezeList(draft.effects),effective:draft.effective});draft.item.game=output;return output;}),partial=units.some(unit=>['partial','unresolved'].includes(unit.selection.loadout.state)||unit.selection.modelCount.state==='unresolved');return frozen({schema:GAME_SCHEMA,status:partial?'partial':'ready',book:frozen({id:catalog.book.id,factionId:catalog.book.id,parentBookId:catalog.book.parentBookId||null}),units:freezeList(units)});
  };
  function project(options={}){
    const catalog=options.catalog||root.WH_BOOK_ROSTER_CATALOG,index=indexCatalog(catalog),roster=options.roster||null,record=options.record||{},compatibility=rosterCompatibility(roster,catalog),rawUnits=list(roster?.units),rawDetachments=list(roster?.detachments?.length?roster.detachments:[roster?.detachment]).filter(Boolean);
    const resolvedDetachments=rawDetachments.map(item=>resolveDetachment(item,index)).filter(Boolean),detachmentIds=new Set(resolvedDetachments.map(item=>item.id)),rawEnhancements=list(roster?.enhancements),resolvedEnhancements=rawEnhancements.map(item=>({input:item,catalog:resolveEnhancement(item,index,detachmentIds)})),projectionUnits=[];
    for(const raw of rawUnits){const unit=index.unitsById.get(raw.canonicalUnitId||raw.unitId)||index.unitsByTitle.get(normalize(raw.name||raw.title));if(!unit)continue;const owned=resolvedEnhancements.filter(item=>item.input.ownerUnitId===raw.id),base={intrinsic:list(unit.intrinsicKeywords),added:grantKeywords(unit,resolvedDetachments),removed:[],state:'known'},providerProfile=options.provider?.keywordProfile?.({raw,unit,roster,record,catalog,index,detachments:resolvedDetachments,enhancements:owned},base)||base;projectionUnits.push({raw,catalogUnit:unit,context:{instanceId:raw.id,canonicalUnitId:unit.id,canonicalDatasheetId:unit.id,title:unit.title,sourceBookId:unit.sourceBookId||catalog.book.id,supplementParent:catalog.book.parentBookId||null,keywordProfile:providerProfile,enhancements:owned.map(item=>({id:item.catalog?.id||item.input.name,title:item.catalog?.title||item.input.name,ownerUnitId:raw.id,status:item.input.ownerStatus||'resolved',detachmentId:item.catalog?.detachmentId||null,provenance:{source:item.input.source||'roster'}})),attachments:explicitFor(record.attachments,raw.id),group:record.groups?.[raw.id]||null,formation:record.formations?.[raw.id]||null,provenance:{sourceRef:raw.sourceRef||'',rosterUnitId:raw.id,canonicalSource:unit.sourceLayer||'current'}}});}
    const attachmentState=attachmentWorkflow.sanitize({attachments:record.attachments,units:projectionUnits.map(item=>({instanceId:item.raw.id,canonicalUnit:item.catalogUnit}))}),projectedRecord={...record,attachments:attachmentState.attachments};for(const item of projectionUnits)item.context.attachments=explicitFor(projectedRecord.attachments,item.raw.id);
    const complete=Boolean(roster)&&compatibility.state!=='incompatible'&&rawUnits.length>0&&projectionUnits.length===rawUnits.length&&resolvedDetachments.length===rawDetachments.length&&resolvedEnhancements.every(item=>item.catalog),context=create({status:complete?'ready':UNKNOWN,bookId:options.bookId||catalog.book.id,factionId:options.factionId||catalog.book.id,parentBookId:options.parentBookId??catalog.book.parentBookId,rosterId:options.rosterId||record.id||null,detachment:resolvedDetachments[0]||null,detachments:resolvedDetachments,enhancements:resolvedEnhancements.map(item=>({id:item.catalog?.id||item.input.name,title:item.catalog?.title||item.input.name,ownerUnitId:item.input.ownerUnitId||'',status:item.input.ownerStatus||'unresolved',detachmentId:item.catalog?.detachmentId||null})),units:projectionUnits.map(item=>item.context),attachments:list(projectedRecord.attachments),groups:list(projectedRecord.groups),formations:list(projectedRecord.formations),provenance:{catalogSchema:catalog.schema,rosterSource:projectedRecord.sourceText?'source-text':'stored-roster'}}),byCanonical=new Map();
    for(const unit of projectionUnits){const items=byCanonical.get(unit.catalogUnit.id)||[];items.push(unit);byCanonical.set(unit.catalogUnit.id,items);}const game=gameProjection({catalog,record:projectedRecord,projectionUnits,detachments:resolvedDetachments,enhancements:resolvedEnhancements,provider:options.provider,roster,index});return {catalog,index,roster,record:projectedRecord,compatibility,context,game,units:projectionUnits,unitsByCanonical:byCanonical,detachments:resolvedDetachments,detachmentIds,enhancements:resolvedEnhancements,attachmentState};
  }
  function fromRuntime(options={}){if(root.WH_ARMY_ROSTER_PROJECTION?.context&&!options.force)return root.WH_ARMY_ROSTER_PROJECTION.context;const input=runtimeInput(options);if(!input.roster)return create({status:input.rosterId?'unavailable':'not-requested',bookId:options.bookId||root.WH_BOOK_ROSTER_CATALOG?.book?.id||'',factionId:options.factionId,parentBookId:options.parentBookId,rosterId:input.rosterId,provenance:{catalogSchema:root.WH_BOOK_ROSTER_CATALOG?.schema||null}});return project({...options,...input}).context;}
  const cardsIn=rootNode=>{const cards=[];if(rootNode?.matches?.('.unit-card'))cards.push(rootNode);return cards.concat([...rootNode?.querySelectorAll?.('.unit-card')||[]]);};
  const markInstance=(card,item,canonicalId)=>{card.dataset.canonicalUnitId=canonicalId;card.dataset.rosterInstance=item.context.instanceId;card.dataset.rosterSelected='true';};
  const requestedInstance=options=>scalar(options?.instanceId)||new URLSearchParams(root.location?.search||'').get('rosterInstance')||scalar(root.history?.state?.whRosterInstance);
  function decorateRoot(rootNode,projection,provider={},options={}){if(!rootNode||!projection?.roster)return rootNode;const requested=requestedInstance(options),cards=cardsIn(rootNode).filter(card=>!card.dataset.rosterGenerated);for(const card of cards){const canonicalId=card.dataset.canonicalUnitId||card.id,instances=projection.unitsByCanonical.get(canonicalId)||[];for(const node of card.parentElement?.querySelectorAll?.('.unit-card[data-roster-generated]')||[])if(node.dataset.rosterGenerated===canonicalId)node.remove();const item=requested?instances.find(candidate=>candidate.context.instanceId===requested):instances.length===1?instances[0]:null;if(!item){card.hidden=true;card.dataset.rosterSelected='false';continue;}card.hidden=false;markInstance(card,item,canonicalId);provider.decorate?.(card,projection,[item]);}const selected=projection.detachmentIds;if(selected.size)for(const section of rootNode.querySelectorAll?.('[data-track^="detachment-"]')||[]){const id=section.dataset.track;if(projection.index.detachmentsById.has(id))section.hidden=!selected.has(id);}return rootNode;}
  function install(options={}){const input=runtimeInput(options);if(!input.roster)return null;let projection=project({...options,...input});if(projection.compatibility.state==='incompatible'){if(root.location?.href&&typeof root.location.replace==='function')root.location.replace(new URL('../../roster-guides/index.html',root.location.href).href);return projection;}const provider=options.providerFactory?.(projection)||options.provider||{};if(provider.keywordProfile||provider.gameEffects)projection=project({...options,...input,provider});root.WH_ARMY_ROSTER_PROJECTION=projection;root.WH_ARMY_ROSTER_GAME_PROJECTION=projection.game;root.WH_ARMY_ROSTER_CONTEXT=projection.context;const decorate=(node,decorateOptions={})=>decorateRoot(node,projection,provider,decorateOptions);root.WH_ARMY_ROSTER_DECORATOR=frozen({decorate,projection});if(options.guideGlobal)root[options.guideGlobal]=frozen({schema:SCHEMA,rosterId:projection.context.rosterId,detachment:projection.context.detachment,detachments:projection.context.detachments,detachmentIds:freezeList([...projection.detachmentIds]),units:projection.context.units,enhancements:projection.context.enhancements,game:projection.game,context:projection.context,warnings:freezeList(projection.roster.warnings)});decorate(options.root||root.document,{instanceId:options.instanceId});root.dispatchEvent?.(new CustomEvent('wh-roster-projection-ready',{detail:{projection}}));return projection;}
  root.WHArmyRosterContext=frozen({SCHEMA,CATALOG_SCHEMA,GAME_SCHEMA,create,project,fromRuntime,decorateRoot,install,indexCatalog,attachments:attachmentWorkflow});root.dispatchEvent?.(new CustomEvent('wh-roster-context-ready'));
}(typeof window==='undefined'?globalThis:window));
