(function(root){
  'use strict';
  const SCHEMA='wh40k-army-roster-context/v1',CATALOG_SCHEMA='wh40k-army-roster-catalog/v1',GAME_SCHEMA='wh40k-physical-unit-game-projection/v1',STORAGE_KEY='wh40k-rosters-v1',UNKNOWN='unknown';
  const normalize=value=>String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),list=value=>Array.isArray(value)?value:[],unique=values=>[...new Set(values.filter(Boolean))],frozen=value=>Object.freeze(value),freezeList=value=>frozen(list(value).map(item=>item&&typeof item==='object'?frozen(item):item));
  const keywordProfile=value=>{const source=value||{},intrinsic=unique(list(source.intrinsic)),added=unique(list(source.added)),removed=unique(list(source.removed)),removedKeys=new Set(removed.map(normalize)),hasEffective=Object.prototype.hasOwnProperty.call(source,'effective'),explicitState=String(source.state||'').trim(),effective=hasEffective?unique(list(source.effective)):explicitState&&explicitState!==UNKNOWN?unique([...intrinsic,...added]).filter(item=>!removedKeys.has(normalize(item))):[],state=explicitState||(hasEffective||intrinsic.length||added.length||removed.length?'known':UNKNOWN);return frozen({intrinsic:freezeList(intrinsic),added:freezeList(added),removed:freezeList(removed),effective:freezeList(effective),state});};
  const unitRecord=unit=>{const keywords=keywordProfile(unit.keywordProfile||unit.keywords),instanceId=scalar(unit.instanceId??unit.id),datasheetId=scalar(unit.datasheetId??unit.canonicalDatasheetId??unit.canonicalUnitId),sourceBookId=scalar(unit.source?.bookId??unit.sourceBookId);return frozen({instanceId,instanceState:scalar(unit.instanceState)||(instanceId?'exact':UNKNOWN),datasheetId,datasheetState:scalar(unit.datasheetState)||(datasheetId?'exact':UNKNOWN),canonicalUnitId:datasheetId,canonicalDatasheetId:datasheetId,title:scalar(unit.title),sourceBookId:sourceBookId||'',source:frozen({bookId:sourceBookId,state:scalar(unit.source?.state??unit.sourceState)||(sourceBookId?'known':UNKNOWN),provenance:scalar(unit.source?.provenance??unit.sourceProvenance)}),supplementParent:unit.supplementParent||null,keywords,keywordProfile:keywords,enhancements:freezeList(unit.enhancements),attachments:freezeList(unit.attachments),group:unit.group?frozen({...unit.group}):null,formation:unit.formation?frozen({...unit.formation}):null,provenance:frozen({...unit.provenance})});};
  const relationGroup=value=>{if(!value)return frozen({state:UNKNOWN,entries:freezeList([])});const source=Array.isArray(value)?{entries:value}:value,entries=list(source.entries).map(entry=>frozen({id:scalar(entry.id),anchorInstanceId:scalar(entry.anchorInstanceId??entry.bodyguardInstanceId),memberInstanceIds:freezeList(unique(list(entry.memberInstanceIds??entry.characterInstanceIds))),instanceIds:freezeList(unique(list(entry.instanceIds))),state:scalar(entry.state)||scalar(source.state)||UNKNOWN,certainty:scalar(entry.certainty)||UNKNOWN,provenance:scalar(entry.provenance)||scalar(source.provenance)}));return frozen({state:scalar(source.state)||(entries.length?'known':UNKNOWN),entries:freezeList(entries)});},relationsProjection=value=>frozen({attachments:relationGroup(value?.attachments),groups:relationGroup(value?.groups),formations:relationGroup(value?.formations)});
  const scalar=value=>value==null||String(value).trim()===''?null:String(value).trim(),bookRecord=input=>{const source=input.book||{},id=scalar(source.id??input.bookId),factionId=scalar(source.factionId??input.factionId??input.bookId),parentBookId=scalar(source.parentBookId??input.parentBookId);return frozen({id,factionId,parentBookId,state:scalar(source.state)||(id?'known':'unknown')});};
  const enhancementRecord=enhancement=>{const instanceId=enhancement.owner?.instanceId??enhancement.ownerInstanceId??enhancement.ownerUnitId??null;return frozen({...enhancement,owner:frozen({...enhancement.owner,instanceId:instanceId==null?null:String(instanceId),state:enhancement.owner?.state??enhancement.ownerState??enhancement.ownerStatus??(instanceId==null?'unknown':'resolved')})});};
  function create(input={}){return frozen({schema:SCHEMA,status:scalar(input.status)||UNKNOWN,book:bookRecord(input),bookId:String(input.bookId||input.book?.id||''),factionId:String(input.factionId||input.book?.factionId||input.bookId||input.book?.id||''),parentBookId:input.parentBookId??input.book?.parentBookId??null,rosterId:scalar(input.rosterId),detachment:input.detachment?frozen({...input.detachment}):null,detachments:freezeList(input.detachments),enhancements:freezeList(list(input.enhancements).map(enhancementRecord)),units:freezeList(list(input.units).map(unitRecord)),relations:relationsProjection(input.relations),attachments:freezeList(input.attachments),groups:freezeList(input.groups),formations:freezeList(input.formations),provenance:frozen({...input.provenance,kind:'runtime-projection',persistenceKey:STORAGE_KEY,persistedSchemaChanged:false})});}
  const indexCatalog=catalog=>{if(!catalog||catalog.schema!==CATALOG_SCHEMA)throw new Error('Canonical roster catalog is unavailable or invalid');const unitsById=new Map(list(catalog.units).map(unit=>[unit.id,unit])),unitsByTitle=new Map(list(catalog.units).map(unit=>[normalize(unit.title),unit])),detachmentsById=new Map(list(catalog.detachments).map(item=>[item.id,item])),detachmentsByTitle=new Map(list(catalog.detachments).map(item=>[normalize(item.title),item])),enhancementsById=new Map(),enhancementsByTitle=new Map();for(const item of list(catalog.enhancements)){for(const id of [item.id,item.ruleId,item.sourceId,item.legacyKey].filter(Boolean))enhancementsById.set(normalize(id),item);const key=normalize(item.title),items=enhancementsByTitle.get(key)||[];items.push(item);enhancementsByTitle.set(key,items);}return {unitsById,unitsByTitle,detachmentsById,detachmentsByTitle,enhancementsById,enhancementsByTitle};};
  const runtimeInput=(options={})=>{if(options.roster)return {roster:options.roster,record:options.record||{},rosterId:options.rosterId||options.record?.id||null};const location=options.location||root.location,storage=options.storage||root.localStorage,rosterId=new URLSearchParams(location?.search||'').get('roster');if(!rosterId||!storage)return {roster:null,record:null,rosterId:null};let records=[];try{records=JSON.parse(storage.getItem('wh40k-rosters-v1')||'[]');}catch{}const record=list(records).find(item=>item?.id===rosterId)||null;if(!record)return {roster:null,record:null,rosterId};const parsed=record.sourceText&&root.WHRosterParser?.parse?root.WHRosterParser.parse(record.sourceText):null;return {roster:parsed?.units?.length?parsed:record.roster||null,record,rosterId};};
  const explicitFor=(source,instanceId)=>{if(!source)return [];if(Array.isArray(source))return source.filter(item=>item?.unitId===instanceId||item?.instanceId===instanceId||item?.sourceId===instanceId);return list(source[instanceId]);};
  const resolveDetachment=(raw,index)=>index.detachmentsById.get(raw?.id)||index.detachmentsByTitle.get(normalize(raw?.name||raw?.label||raw))||null;
  const resolveEnhancement=(raw,index,detachmentIds)=>{const byId=index.enhancementsById.get(normalize(raw?.ruleId||raw?.id));if(byId)return byId;const candidates=index.enhancementsByTitle.get(normalize(raw?.name||raw?.title))||[];return candidates.find(item=>!item.detachmentId||detachmentIds.has(item.detachmentId))||candidates[0]||null;};
  const grantKeywords=(unit,detachments)=>{const added=[];for(const detachment of detachments)for(const grant of list(detachment.keywordGrants)){const ids=list(grant.unitIds||grant.units),titles=list(grant.unitTitles||grant.titles).map(normalize);if((!ids.length&&!titles.length)||ids.includes(unit.id)||titles.includes(normalize(unit.title)))added.push(...list(grant.add||grant.keywords),...(grant.keyword?[grant.keyword]:[]));}return added;};
  const identityParts=value=>unique(String(value||'').split(/\s+-\s+/).map(normalize));
  const rosterCompatibility=(roster,catalog)=>{const rosterIdentities=identityParts(roster?.faction??roster?.factionId),book=catalog.book||{},catalogIdentities=unique([book.id,book.title,book.factionKeyword,book.parentBookId,...list(book.dependencies).flatMap(item=>[item?.bookId,item?.id,item?.title])].flatMap(identityParts));return frozen({state:!rosterIdentities.length?'unknown':rosterIdentities.some(identity=>catalogIdentities.includes(identity))?'compatible':'incompatible',rosterIdentities:freezeList(rosterIdentities),catalogIdentities:freezeList(catalogIdentities)});};
  const splitSelections=value=>{const output=[];let depth=0,start=0,text=String(value||'');for(let index=0;index<text.length;index++){if(text[index]==='(')depth++;else if(text[index]===')')depth=Math.max(0,depth-1);else if(text[index]===','&&depth===0){output.push(text.slice(start,index));start=index+1;}}output.push(text.slice(start));return output.map(item=>item.trim()).filter(Boolean);};
  const selectionText=value=>String(value||'').replace(/^\s*\d+\s*[x\u00d7]?\s+/i,'').trim();
  const selectionInputs=raw=>{const rows=[];const add=(value,quantity,model)=>{for(const sourceText of splitSelections(value))rows.push({sourceText,matchText:selectionText(sourceText),quantity:Number(quantity)||null,model:model||null});};if(list(raw?.models).length)for(const model of raw.models){if(list(model.loadouts).length)for(const loadout of model.loadouts)add(loadout.wargear,loadout.quantity??model.quantity,model.name);else add(model.wargear,model.quantity,model.name);}else add(raw?.wargear,raw?.quantity,raw?.name);return rows;};
  const resolvedValue=(value,state,provenance)=>frozen({value,state,provenance:frozen(provenance)});
  const resolveGameSelection=(input,metadata)=>{const candidates=list(metadata?.selections).filter(selection=>unique([selection.title,...list(selection.aliases)]).some(alias=>normalize(alias)===normalize(input.matchText)));if(candidates.length!==1)return frozen({...input,state:candidates.length?'ambiguous':'unresolved',reason:candidates.length?'multiple-selection-candidates':'no-canonical-alias',candidateIds:freezeList(candidates.map(item=>item.id)),profileIds:freezeList([]),wargearAbilityIds:freezeList([])});const selection=candidates[0],missingAbility=list(selection.candidateWargearAbilityIds).length&&!list(selection.wargearAbilityIds).length;return frozen({...input,selectionId:selection.id,canonicalTitle:selection.title,kind:selection.kind||'wargear',profileIds:freezeList(selection.profileIds),wargearAbilityIds:freezeList(selection.wargearAbilityIds),state:missingAbility?'unresolved':'resolved',reason:missingAbility?'missing-wargear-ability-link':null,candidateIds:freezeList(missingAbility?selection.candidateWargearAbilityIds:[]),provenance:frozen({kind:'canonical-roster-selection',catalogSchema:CATALOG_SCHEMA})});};
  const freezeEffect=(effect,instanceId)=>frozen({...effect,targetInstanceId:effect.targetInstanceId||instanceId,state:effect.state||'active',certainty:effect.certainty||'current',source:frozen({...effect.source}),condition:effect.condition?frozen({...effect.condition}):null,provenance:frozen({kind:'curated-provider',...effect.provenance})});
  const gameProjection=({catalog,record,projectionUnits,detachments,enhancements,provider,roster,index})=>{
    const drafts=projectionUnits.map(item=>{const raw=item.raw,metadata=item.catalogUnit.gameSelections||{},models=list(raw.models),validModels=models.length&&models.every(model=>Number.isFinite(Number(model.quantity))&&Number(model.quantity)>=0),modelCount=validModels?models.reduce((sum,model)=>sum+Number(model.quantity),0):null,inputs=selectionInputs(raw),resolved=inputs.map(input=>resolveGameSelection(input,metadata)),selectedProfileIds=unique(resolved.flatMap(item=>item.state==='resolved'?list(item.profileIds):[])),selectedWargearAbilityIds=unique(resolved.flatMap(item=>item.state==='resolved'?list(item.wargearAbilityIds):[])),unresolved=resolved.filter(item=>item.state!=='resolved'),selectionState=!inputs.length?'not-provided':unresolved.length===inputs.length?'unresolved':unresolved.length?'partial':'resolved';return {item,identity:{instanceId:raw.id,canonicalDatasheetId:item.catalogUnit.id,canonicalTitle:item.catalogUnit.title,sourceBookId:item.context.sourceBookId,supplementParent:item.context.supplementParent,state:'resolved'},selection:{modelCount:resolvedValue(modelCount,validModels?'resolved':models.length?'unresolved':'not-provided',{kind:'parsed-roster-models',sourceRef:raw.sourceRef||''}),points:resolvedValue(Number.isFinite(Number(raw.points))?Number(raw.points):null,Number.isFinite(Number(raw.points))?'resolved':'not-provided',{kind:'parsed-roster-unit',sourceRef:raw.sourceRef||''}),composition:{state:validModels?'resolved':models.length?'unresolved':'not-provided',models:models.map(model=>frozen({sourceText:model.name||'',quantity:Number(model.quantity)||0,state:'resolved'})),unresolved:freezeList([])},loadout:{state:selectionState,weapons:freezeList(resolved.filter(item=>item.kind==='weapon')),wargear:freezeList(resolved.filter(item=>item.kind!=='weapon')),selectedProfileIds:freezeList(selectedProfileIds),selectedWargearAbilityIds:freezeList(selectedWargearAbilityIds),unresolved:freezeList(unresolved)}},rosterState:{detachments:freezeList(detachments.map(item=>item.id)),enhancements:freezeList(item.context.enhancements),keywordProfile:item.context.keywordProfile},attachments:{leaders:[],leading:[]},effects:[]};});
    const byInstance=new Map(drafts.map(draft=>[draft.identity.instanceId,draft]));
    const relation=(direction,other,bodyguardInstanceId,leaderInstanceId)=>frozen({direction,instanceId:other.identity.instanceId,canonicalUnitId:other.identity.canonicalDatasheetId,certainty:'current',provenance:frozen({kind:'explicit-roster-attachment',persistenceKey:STORAGE_KEY,bodyguardInstanceId,leaderInstanceId})});
    for(const [bodyguardId,leaderIds] of Object.entries(record.attachments||{})){const bodyguard=byInstance.get(bodyguardId);if(!bodyguard)continue;for(const leaderId of list(leaderIds)){const leader=byInstance.get(typeof leaderId==='string'?leaderId:leaderId?.unitId||leaderId?.instanceId);if(!leader)continue;bodyguard.attachments.leaders.push(relation('leader',leader,bodyguardId,leader.identity.instanceId));leader.attachments.leading.push(relation('leading',bodyguard,bodyguardId,leader.identity.instanceId));}}
    const shared={catalog,index,roster,record,detachments,enhancements,units:projectionUnits,gameUnits:drafts,byInstance};
    for(const draft of drafts){const effects=list(provider?.gameEffects?.({...shared,item:draft.item,gameUnit:draft})||[]);draft.effects=effects.map(effect=>freezeEffect(effect,draft.identity.instanceId));}
    const units=drafts.map(draft=>{const output=frozen({identity:frozen(draft.identity),selection:frozen({...draft.selection,composition:frozen({...draft.selection.composition,models:freezeList(draft.selection.composition.models)}),loadout:frozen(draft.selection.loadout)}),rosterState:frozen(draft.rosterState),attachments:frozen({leaders:freezeList(draft.attachments.leaders),leading:freezeList(draft.attachments.leading)}),effects:freezeList(draft.effects)});draft.item.game=output;return output;}),partial=units.some(unit=>['partial','unresolved'].includes(unit.selection.loadout.state)||unit.selection.modelCount.state==='unresolved');return frozen({schema:GAME_SCHEMA,status:partial?'partial':'ready',book:frozen({id:catalog.book.id,factionId:catalog.book.id,parentBookId:catalog.book.parentBookId||null}),units:freezeList(units)});
  };
  function project(options={}){
    const catalog=options.catalog||root.WH_BOOK_ROSTER_CATALOG,index=indexCatalog(catalog),roster=options.roster||null,record=options.record||{},compatibility=rosterCompatibility(roster,catalog),rawUnits=list(roster?.units),rawDetachments=list(roster?.detachments?.length?roster.detachments:[roster?.detachment]).filter(Boolean);
    const resolvedDetachments=rawDetachments.map(item=>resolveDetachment(item,index)).filter(Boolean),detachmentIds=new Set(resolvedDetachments.map(item=>item.id)),rawEnhancements=list(roster?.enhancements),resolvedEnhancements=rawEnhancements.map(item=>({input:item,catalog:resolveEnhancement(item,index,detachmentIds)})),projectionUnits=[];
    for(const raw of rawUnits){const unit=index.unitsById.get(raw.canonicalUnitId||raw.unitId)||index.unitsByTitle.get(normalize(raw.name||raw.title));if(!unit)continue;const owned=resolvedEnhancements.filter(item=>item.input.ownerUnitId===raw.id),base={intrinsic:list(unit.intrinsicKeywords),added:grantKeywords(unit,resolvedDetachments),removed:[],state:'known'},providerProfile=options.provider?.keywordProfile?.({raw,unit,roster,record,catalog,index,detachments:resolvedDetachments,enhancements:owned},base)||base;projectionUnits.push({raw,catalogUnit:unit,context:{instanceId:raw.id,canonicalUnitId:unit.id,canonicalDatasheetId:unit.id,title:unit.title,sourceBookId:unit.sourceBookId||catalog.book.id,supplementParent:catalog.book.parentBookId||null,keywordProfile:providerProfile,enhancements:owned.map(item=>({id:item.catalog?.id||item.input.name,title:item.catalog?.title||item.input.name,ownerUnitId:raw.id,status:item.input.ownerStatus||'resolved',detachmentId:item.catalog?.detachmentId||null,provenance:{source:item.input.source||'roster'}})),attachments:explicitFor(record.attachments,raw.id),group:record.groups?.[raw.id]||null,formation:record.formations?.[raw.id]||null,provenance:{sourceRef:raw.sourceRef||'',rosterUnitId:raw.id,canonicalSource:unit.sourceLayer||'current'}}});}
    const complete=Boolean(roster)&&compatibility.state!=='incompatible'&&rawUnits.length>0&&projectionUnits.length===rawUnits.length&&resolvedDetachments.length===rawDetachments.length&&resolvedEnhancements.every(item=>item.catalog),context=create({status:complete?'ready':UNKNOWN,bookId:options.bookId||catalog.book.id,factionId:options.factionId||catalog.book.id,parentBookId:options.parentBookId??catalog.book.parentBookId,rosterId:options.rosterId||record.id||null,detachment:resolvedDetachments[0]||null,detachments:resolvedDetachments,enhancements:resolvedEnhancements.map(item=>({id:item.catalog?.id||item.input.name,title:item.catalog?.title||item.input.name,ownerUnitId:item.input.ownerUnitId||'',status:item.input.ownerStatus||'unresolved',detachmentId:item.catalog?.detachmentId||null})),units:projectionUnits.map(item=>item.context),attachments:list(record.attachments),groups:list(record.groups),formations:list(record.formations),provenance:{catalogSchema:catalog.schema,rosterSource:record.sourceText?'source-text':'stored-roster'}}),byCanonical=new Map();
    for(const unit of projectionUnits){const items=byCanonical.get(unit.catalogUnit.id)||[];items.push(unit);byCanonical.set(unit.catalogUnit.id,items);}const game=gameProjection({catalog,record,projectionUnits,detachments:resolvedDetachments,enhancements:resolvedEnhancements,provider:options.provider,roster,index});return {catalog,index,roster,record,compatibility,context,game,units:projectionUnits,unitsByCanonical:byCanonical,detachments:resolvedDetachments,detachmentIds,enhancements:resolvedEnhancements};
  }
  function fromRuntime(options={}){if(root.WH_ARMY_ROSTER_PROJECTION?.context&&!options.force)return root.WH_ARMY_ROSTER_PROJECTION.context;const input=runtimeInput(options);if(!input.roster)return create({status:input.rosterId?'unavailable':'not-requested',bookId:options.bookId||root.WH_BOOK_ROSTER_CATALOG?.book?.id||'',factionId:options.factionId,parentBookId:options.parentBookId,rosterId:input.rosterId,provenance:{catalogSchema:root.WH_BOOK_ROSTER_CATALOG?.schema||null}});return project({...options,...input}).context;}
  const cardsIn=rootNode=>{const cards=[];if(rootNode?.matches?.('.unit-card'))cards.push(rootNode);return cards.concat([...rootNode?.querySelectorAll?.('.unit-card')||[]]);},stableState=item=>JSON.stringify({points:item.raw.points,models:item.raw.models,wargear:item.raw.wargear,enhancements:item.context.enhancements,attachments:item.context.attachments,group:item.context.group});
  const markInstance=(card,item,canonicalId)=>{card.dataset.canonicalUnitId=canonicalId;card.dataset.rosterInstance=item.context.instanceId;card.dataset.rosterSelected='true';};
  function decorateRoot(rootNode,projection,provider={}){if(!rootNode||!projection?.roster)return rootNode;const cards=cardsIn(rootNode).filter(card=>!card.dataset.rosterGenerated);for(const card of cards){const canonicalId=card.dataset.canonicalUnitId||card.id,instances=projection.unitsByCanonical.get(canonicalId)||[];for(const node of card.parentElement?.querySelectorAll?.('.unit-card[data-roster-generated]')||[])if(node.dataset.rosterGenerated===canonicalId)node.remove();if(!instances.length){card.hidden=true;card.dataset.rosterSelected='false';continue;}card.hidden=false;const groups=new Map();for(const item of instances){const key=provider.stateKey?.(item.raw,projection,item)||stableState(item),group=groups.get(key)||[];group.push(item);groups.set(key,group);}[...groups.values()].forEach((items,index)=>{const target=index===0?card:card.cloneNode(true),item=items[0];if(index){target.id=`${canonicalId}--${item.context.instanceId}`;target.dataset.rosterGenerated=canonicalId;card.parentElement?.insertBefore(target,card.nextSibling);}markInstance(target,item,canonicalId);provider.decorate?.(target,projection,items);});}const selected=projection.detachmentIds;if(selected.size)for(const section of rootNode.querySelectorAll?.('[data-track^="detachment-"]')||[]){const id=section.dataset.track;if(projection.index.detachmentsById.has(id))section.hidden=!selected.has(id);}return rootNode;}
  function install(options={}){const input=runtimeInput(options);if(!input.roster)return null;let projection=project({...options,...input});if(projection.compatibility.state==='incompatible'){if(root.location?.href&&typeof root.location.replace==='function')root.location.replace(new URL('../../roster-guides/index.html',root.location.href).href);return projection;}const provider=options.providerFactory?.(projection)||options.provider||{};if(provider.keywordProfile||provider.gameEffects)projection=project({...options,...input,provider});root.WH_ARMY_ROSTER_PROJECTION=projection;root.WH_ARMY_ROSTER_GAME_PROJECTION=projection.game;root.WH_ARMY_ROSTER_CONTEXT=projection.context;const decorate=node=>decorateRoot(node,projection,provider);root.WH_ARMY_ROSTER_DECORATOR=frozen({decorate,projection});if(options.guideGlobal)root[options.guideGlobal]=frozen({schema:SCHEMA,rosterId:projection.context.rosterId,detachment:projection.context.detachment,detachments:projection.context.detachments,detachmentIds:freezeList([...projection.detachmentIds]),units:projection.context.units,enhancements:projection.context.enhancements,game:projection.game,context:projection.context,warnings:freezeList(projection.roster.warnings)});decorate(options.root||root.document);root.dispatchEvent?.(new CustomEvent('wh-roster-projection-ready',{detail:{projection}}));return projection;}
  root.WHArmyRosterContext=frozen({SCHEMA,CATALOG_SCHEMA,GAME_SCHEMA,create,project,fromRuntime,decorateRoot,install,indexCatalog});root.dispatchEvent?.(new CustomEvent('wh-roster-context-ready'));
}(typeof window==='undefined'?globalThis:window));
