import assert from 'node:assert/strict';
import {existsSync,readFileSync,readdirSync} from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url)),book=path.resolve(here,'..'),root=path.resolve(book,'../..'),read=file=>readFileSync(file,'utf8'),json=file=>JSON.parse(read(file));
const reader=read(path.join(book,'reader.html')),targetScript=read(path.join(book,'scripts/target-data.js')).trim(),targetData=JSON.parse(targetScript.slice('window.WH_ARMY_BOOK_TARGETS=Object.freeze('.length,-2)),source=targetData.html,config=json(path.join(book,'book.config.json')),manifest=json(path.join(book,config.sources.manifest)),app=read(path.join(book,'scripts/app.js')),related=read(path.join(here,'related-rules.inc'));
const detachments=[...source.matchAll(/<section class="content-group detachment" id="(detachment-[^"]+)"/g)].map(match=>match[1]),unitIds=[...source.matchAll(/<article class="unit-card\b[^>]*\bid="(unit-[^"]+)"/g)].map(match=>match[1]),localData=json(path.join(book,config.sources.codexDatasheets)),localIds=new Set(localData.datasheets.map(unit=>unit.id)),sharedIds=unitIds.filter(id=>!localIds.has(id)),routeIds=['start','army-rules',...detachments,...unitIds,'updates'],files=new Set(['index.html','army-rules.html','updates.html',...detachments.map(id=>`${id.slice(11)}.html`),...unitIds.map(id=>`${id.slice(5)}.html`)]);
assert.equal(config.generatedMobile,true);assert.equal(manifest.gates?.publishAsComplete,false);assert.equal(detachments.length,24);assert.equal(localIds.size,15);assert.equal(sharedIds.length,82);assert.equal(unitIds.length,97);assert.equal(files.size,124);assert.equal(new Set(routeIds).size,124);
const htmlFiles=readdirSync(here).filter(file=>file.endsWith('.html'));assert.deepEqual([...files].filter(file=>!existsSync(path.join(here,file))),[]);assert.deepEqual(htmlFiles.filter(file=>!files.has(file)),[]);
for(const routeId of routeIds){const file=routeId==='start'?'index.html':routeId==='army-rules'?'army-rules.html':routeId==='updates'?'updates.html':routeId.startsWith('detachment-')?`${routeId.slice(11)}.html`:`${routeId.slice(5)}.html`,html=read(path.join(here,file)),target=routeId==='army-rules'?'army-rule-oath-of-moment':routeId==='updates'?'update-rules-updates-9':routeId;assert.match(html,/data-canonical-reader="\.\.\/reader\.html"/);assert.match(html,new RegExp(`data-canonical-target="${target}"`));assert.match(html,/\.\.\/\.\.\/shared\/mobile-route-redirect\.js\?v=\d+/);assert.doesNotMatch(html,/<(?:article|section)\b|class="[^"]*\bunit-card\b|data-rule-id=/);}
const dependency=config.dependencyDatasheets||{},dependencyBook=dependency.book||dependency.books?.[0]||'space-marines',dependencyConfig=json(path.join(root,'books',dependencyBook,'book.config.json')),dependencyData=json(path.join(root,'books',dependencyBook,dependencyConfig.sources.codexDatasheets)),excluded=new Set((dependency.excludeAnyKeywords||[]).map(value=>String(value).toUpperCase()));for(const unit of dependencyData.datasheets||[])if((unit.keywords||[]).some(keyword=>excluded.has(String(keyword).toUpperCase())))assert.ok(!unitIds.includes(unit.id));for(const unit of [...(localData.legends||[]),...(dependencyData.legends||[])])assert.ok(!unitIds.includes(unit.id));
assert.match(source,/surge move of up to D6\+2&quot;/);assert.match(source,/re-roll Charge rolls[\s\S]*Heroic Intervention stratagem[\s\S]*‑1 CP/);assert.match(source,/id="sanguinary-priest-support"[\s\S]*<h4>Support<\/h4>/);assert.match(source,/BATTLELINE[\s\S]*DOOMED[\s\S]*cannot include any ADEPTUS ASTARTES units drawn from any other Chapter/);assert.match(reader,/\.\.\/shared\/book-roster-enhancements\.js\?v=\d+/);assert.match(app,/related-rules\.inc/);assert.match(related,/class="stratagem surface"/);assert.ok(!existsSync(path.join(here,'mobile.js'))&&!existsSync(path.join(here,'mobile.css'))&&!existsSync(path.join(here,'phone-popup-controller.js')));
console.log(`Blood Angels responsive QA passed: ${files.size} content-free routes, ${detachments.length} Detachments, ${localIds.size} local and ${sharedIds.length} shared datasheets.`);
