import {readFile,writeFile} from 'node:fs/promises';

const source=await readFile(new URL('../reader.html',import.meta.url),'utf8');
const glossary=JSON.parse(await readFile(new URL('../../../glossary/registry.en.json',import.meta.url),'utf8')).terms;
const aliases=JSON.parse(await readFile(new URL('../../../glossary/aliases.en.json',import.meta.url),'utf8')).aliases;
const glossaryContext=JSON.parse(await readFile(new URL('../../../glossary/contexts/tau-empire.json',import.meta.url),'utf8')).terms;
const relatedSource=await readFile(new URL('related-rules.source.inc',import.meta.url),'utf8');
const mobileRulePaths=new Map();
function extract(tag,id,html=source){
  const opener=new RegExp(`<${tag}\\b[^>]*\\bid="${id}"[^>]*>`,'i').exec(html);if(!opener)throw new Error(`Missing ${tag}#${id}`);
  const tags=new RegExp(`<\\/?${tag}\\b[^>]*>`,'gi');tags.lastIndex=opener.index;let depth=0;
  for(let match;(match=tags.exec(html));){depth+=match[0][1]==='/'?-1:1;if(depth===0)return html.slice(opener.index,tags.lastIndex);}
  throw new Error(`Unclosed ${tag}#${id}`);
}
const clean=value=>value.replace(/<[^>]+>/g,'').replace(/&amp;/g,'&').trim();
const attr=value=>String(value).replaceAll('&','&amp;').replaceAll('"','&quot;').replaceAll('<','&lt;');
const portable=html=>html.replaceAll('href="./sources/','href="../sources/').replaceAll('src="./assets/','src="../assets/');
function hydrate(html){return html.replace(/(<(?:button|a)\b[^>]*\bdata-term="([^"]+)"[^>]*)(>)/g,(match,start,id,end)=>{
  const context=glossaryContext[id]||glossaryContext[aliases[id]||id],term=glossary[aliases[context?.termId]||context?.termId||aliases[id]||id];
  if(!term)throw new Error(`Missing glossary term ${id}`);
  const title=term.title?.en||id,summary=term.kind==='stratagem'?term.definition?.en||term.summary?.en||'':term.summary?.en||term.definition?.en||'';
  const fullRulePath=context?.navigation?.fullRulePath||term.fullRulePath||'',anchor=fullRulePath.includes('#')?fullRulePath.slice(fullRulePath.indexOf('#')+1):'',mobileRulePath=/books\/tau-empire\/(?:index|reader)\.html#/.test(fullRulePath)?mobileRulePaths.get(anchor)||'':'';
  return`${start} data-term-title="${attr(title)}" data-term-summary="${attr(summary)}"${fullRulePath?` data-full-rule-path="${attr(fullRulePath)}"`:''}${mobileRulePath?` data-mobile-rule-path="${attr(mobileRulePath)}"`:''}${end}`;
});}
const detachments=[...source.matchAll(/<section class="content-group detachment" id="(detachment-[^"]+)"[^>]*>\s*<h3 class="category-title detachment-title">([^<]+)\s*<span class="detachment-dp">([^<]+)<\/span><\/h3>/g)].map(([,id,title,dp])=>({id,title:clean(title),dp:clean(dp),file:`${id.slice(11)}.html`,type:'detachment'}));
const categories=[...source.matchAll(/<section class="content-group" id="(datasheets-[^"]+)"[^>]*>\s*<h3 class="category-title">([^<]+)<\/h3>/g)].map(([,id,title])=>{
  const section=extract('section',id),units=[...section.matchAll(/<article\b[^>]*\bclass="[^"]*\bunit-card\b[^"]*"[^>]*\bid="(unit-[^"]+)"[^>]*>/g)].map(([,unitId])=>{
    const article=extract('article',unitId,section),unitTitle=/<h3(?: class="unit-name")?>([\s\S]*?)<\/h3>/.exec(article)?.[1];if(!unitTitle)throw new Error(`Missing title for ${unitId}`);
    const ruleFacts=JSON.parse((/\bdata-rule-facts="([^"]*)"/.exec(article)?.[1]||'{}').replaceAll('&quot;','"').replaceAll('&amp;','&'));return{id:unitId,title:clean(unitTitle),file:`${unitId.slice(5)}.html`,type:'unit',category:id,enhancementsAllowed:!ruleFacts.epic};
  });return{id,title:clean(title),units};
});
const units=categories.flatMap(category=>category.units);if(detachments.length!==7||units.length!==63)throw new Error(`Expected 7 detachments and 63 datasheets, found ${detachments.length} and ${units.length}`);
const staticRoutes=[{file:'index.html',id:'start',title:'Start',type:'start'},{file:'army-rules.html',id:'army-rules',title:'Army Rules',type:'army-rules'},{file:'updates.html',id:'updates',title:'Updates',type:'section'}],routes=[...staticRoutes,...detachments,...units];
const content=route=>portable(route.type==='start'?extract('section','start'):route.type==='army-rules'?extract('section','army-rules'):route.type==='section'||route.type==='detachment'?extract('section',route.id):extract('article',route.id));
for(const route of routes)for(const[,id]of content(route).matchAll(/\sid="([^"]+)"/g))mobileRulePaths.set(id,`books/tau-empire/mobile/${route.file}#${id}`);
function navigation(route){
  const category=categories.find(item=>item.id===route.category),link=item=>`<a href="./${item.file}"${item.id===route.id?' aria-current="page"':''}>${item.title}${item.dp?` <span class="detachment-dp">${item.dp}</span>`:''}</a>`;
  return`${staticRoutes.slice(0,2).map(link).join('')}<details name="mobile-primary"${route.type==='detachment'?' open':''}><summary>Detachments <span>${detachments.length}</span></summary><div class="mobile-nav-branch">${detachments.map(link).join('')}</div></details><details name="mobile-primary"${route.type==='unit'?' open':''}><summary>Datasheets <span>${units.length}</span></summary><div class="mobile-nav-branch mobile-unit-groups">${categories.map(group=>`<details${group===category?' open':''}><summary>${group.title} <span>${group.units.length}</span></summary><div class="mobile-nav-branch">${group.units.map(link).join('')}</div></details>`).join('')}</div></details>${link(staticRoutes[2])}`;
}
function page(route){
  const related=route.type==='unit'?`<section class="related-rules" id="relatedRules" aria-labelledby="relatedRulesTitle"><header class="related-rules-head"><div><span>Datasheet tools</span><h2 id="relatedRulesTitle">${route.enhancementsAllowed?'Compatible Stratagems &amp; Enhancements':'Compatible Stratagems'}</h2></div></header><div class="related-controls"><label>Detachment<select id="relatedDetachment"><option value="all">All detachments</option>${detachments.map(item=>`<option value="${item.id.slice(11)}">${item.title}</option>`).join('')}</select></label>${route.enhancementsAllowed?'<div class="related-tabs" role="group" aria-label="Rule type"><button type="button" data-related-tab="stratagems" aria-pressed="true">Stratagems</button><button type="button" data-related-tab="enhancements" aria-pressed="false">Enhancements</button></div>':''}</div><div class="related-content" id="relatedRulesContent"><p class="related-status">Loading rules&hellip;</p></div></section>`:'';
  return`<!doctype html><html lang="en" data-theme="dark" data-book-id="tau-empire"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#0a0b0d"><title>${route.title} &mdash; T&rsquo;au Empire</title><link rel="manifest" href="../../../manifest.webmanifest"><link rel="stylesheet" href="../../death-guard/styles/tokens.css?v=11"><link rel="stylesheet" href="../styles/tokens.css?v=3"><link rel="stylesheet" href="../../death-guard/styles/layout.css?v=11"><link rel="stylesheet" href="../../death-guard/styles/navigation.css?v=12"><link rel="stylesheet" href="../../death-guard/styles/content.css?v=37"><link rel="stylesheet" href="../../death-guard/styles/popups.css?v=17"><link rel="stylesheet" href="../../shared/datasheet-system.css?v=6"><link rel="stylesheet" href="../styles/book.css?v=4"><link rel="stylesheet" href="./mobile.css?v=1"></head><body><header class="app-header" id="appHeader"><button class="header-button nav-menu" id="navButton" aria-label="Open navigation" aria-controls="mobileNav" aria-expanded="false">&#9776;</button><div class="app-brand"><strong>T&rsquo;au Empire Rules</strong><small>11E &middot; Mobile reference</small></div><a class="library-link" href="../../../index.html"><span>&larr;</span><b>Library</b></a><div class="header-spacer"></div></header><button class="toc-scrim" id="navScrim" aria-label="Close navigation" hidden></button><nav class="toc-panel" id="mobileNav" aria-label="T'au Empire navigation" aria-hidden="true"><h2 class="toc-heading">Contents</h2><div class="phone-shortcuts"><a class="phone-glossary" href="../../../glossary/index.html">Mega Glossary &rarr;</a><a class="phone-glossary" href="../reader.html#${route.id}" data-view-switch>Desktop / iPad view &rarr;</a></div><div class="phone-tree">${navigation(route)}</div></nav><main class="main mobile-main"><article class="document">${hydrate(content(route))}${related}</article><a class="return-popup" id="returnPopup" hidden>Return to popup</a></main><script src="../../shared/datasheet-layout.js?v=2"></script><script src="../../shared/rule-facts.js?v=1"></script><script src="../../shared/related-rules-matcher.js?v=4"></script><script src="../../shared/army-related-rules.js?v=6"></script><dialog class="mobile-dialog" id="termDialog" aria-labelledby="termTitle"><form method="dialog" class="mobile-dialog-head"><span>Mega Glossary</span><button aria-label="Close popup">&times;</button></form><h2 id="termTitle"></h2><p id="termSummary"></p><a id="termRule" hidden>Open full rule &rarr;</a><a id="termFull" href="../../../glossary/index.html">Glossary entry &rarr;</a></dialog><script src="../../../glossary-return.js?v=3"></script><script src="../../shared/roster-parser.js?v=2"></script><script src="../scripts/roster-data.js?v=1"></script><script src="../../shared/book-roster-enhancements.js?v=1"></script><script src="./mobile.js?v=4"></script></body></html>`;
}
for(const route of routes)await writeFile(new URL(route.file,import.meta.url),page(route).replace('../styles/book.css?v=4','../styles/book.css?v=5').replace('army-related-rules.js?v=6','army-related-rules.js?v=9').replace('related-rules-matcher.js?v=4','related-rules-matcher.js?v=6').replace('rule-facts.js?v=1','rule-facts.js?v=4').replace('<script src="../scripts/roster-data.js?v=1"></script>','<script src="../../shared/roster-entities.js?v=1"></script><script src="../scripts/roster-data.js?v=1"></script>'));
await writeFile(new URL('related-rules.inc',import.meta.url),hydrate(portable(relatedSource.replace(/\sdata-(?:term-title|term-summary|full-rule-path|mobile-rule-path)="[^"]*"/g,''))));
console.log(`TвЂ™au Empire mobile reference built: ${routes.length} pages, ${detachments.length} detachments, ${units.length} datasheets.`);
