(async function(){
  'use strict';
  const scriptUrl=document.currentScript.src,navButton=document.getElementById('navButton'),scrim=document.getElementById('navScrim'),nav=document.getElementById('mobileNav');
  const dialog=document.getElementById('termDialog'),title=document.getElementById('termTitle'),summary=document.getElementById('termSummary'),full=document.getElementById('termFull'),rule=document.getElementById('termRule'),returnPopup=document.getElementById('returnPopup');
  const related=document.getElementById('relatedRules'),content=document.getElementById('relatedRulesContent'),select=document.getElementById('relatedDetachment'),unit=document.querySelector('.unit-card'),normalize=value=>String(value||'').toLowerCase().replace(/\[legends\]/g,'').replace(/[^a-z0-9]+/g,' ').trim();
  const compatibleRuntime=await import(new URL('../scripts/compatible-rules-runtime.mjs?v=1',scriptUrl)).catch(error=>{console.warn('Compatible rules unavailable.',error);return null;});
  const rosterId=new URLSearchParams(location.search).get('roster');let roster=null,selected=new Map(),rosterDetachments=new Set(),rosterValid=!rosterId,opener=null,loaded=false,kind='stratagems',compatibleMatrix,assignedEnhancementRuleIds=new Set();
  let relatedRulesEnabled=Boolean(compatibleRuntime&&related);
  const viewSwitch=document.querySelector('[data-view-switch]');if(viewSwitch){const url=new URL(viewSwitch.href);url.search=location.search;if(location.hash)url.hash=location.hash;viewSwitch.href=url.href;}
  if(rosterId)try{
    const record=(JSON.parse(localStorage.getItem('wh40k-rosters-v1'))||[]).find(item=>item?.id===rosterId);if(!record)throw new Error('Roster data unavailable');roster=record.sourceText&&window.WHRosterParser?window.WHRosterParser.parse(record.sourceText):record.roster;if(!['t au empire','tau empire'].includes(normalize(roster?.faction))||!roster?.units?.length)throw new Error('Roster data unavailable');
    for(const item of roster.units){const key=normalize(item.name),entry=selected.get(key)||{units:[],loadout:[]};entry.units.push(item);entry.loadout.push(...[item.wargear,...(item.models||[]).flatMap(model=>[model.wargear,...(model.loadouts||[]).map(loadout=>loadout.wargear)])].filter(Boolean));selected.set(key,entry);}
    rosterDetachments=new Set((roster.detachments?.length?roster.detachments.map(item=>item.label):[roster.detachment]).flatMap(value=>String(value||'').split(/\s*,\s*(?![^()]*\))/)).map(value=>normalize(value.replace(/\s*\([^)]*\)\s*$/,''))).filter(Boolean));
    for(const link of nav.querySelectorAll('a[href$=".html"]')){const url=new URL(link.href);url.searchParams.set('roster',rosterId);link.href=url.href;if(/\/(?:mobile\/)?[^/]+\.html$/.test(url.pathname)&&link.closest('.mobile-unit-groups'))link.hidden=!selected.has(normalize(link.textContent));}
    for(const link of nav.querySelectorAll('.phone-tree > details:first-of-type .mobile-nav-branch > a'))link.hidden=!rosterDetachments.has(normalize(link.textContent));for(const group of nav.querySelectorAll('.mobile-unit-groups > details'))group.hidden=![...group.querySelectorAll('a')].some(link=>!link.hidden);
    if(unit){const entry=selected.get(normalize(unit.dataset.unitTitle));if(!entry)throw new Error('Roster data unavailable');window.WHBookRosterEnhancements?.decorate(unit,roster,entry.units);const composition=unit.querySelector('[id$="-composition"]');if(composition){const block=document.createElement('div');block.className='content-block roster-composition';const heading=document.createElement('strong');heading.textContent='Roster loadout';const list=document.createElement('ul');for(const item of entry.units){const row=document.createElement('li');row.textContent=`${item.quantity||1}× ${item.name}${item.wargear?` — ${item.wargear}`:''}`;list.append(row);}block.append(heading,list);composition.replaceChildren(composition.querySelector('h4'),block);}if(entry.loadout.length&&window.WHRosterEntities)unit.querySelectorAll('.weapon-row:not(.weapon-head)').forEach(row=>{const label=row.querySelector('.weapon-button')?.textContent||row.firstElementChild?.textContent;if(label&&!window.WHRosterEntities.loadoutIncludesProfile(entry.loadout,label))row.remove();});}
    rosterValid=true;document.documentElement.dataset.rosterActive='true';document.querySelector('[data-roster-guides-link]')?.removeAttribute('hidden');
  }catch(error){console.warn("T'au roster unavailable",error);relatedRulesEnabled=false;}
  if(!relatedRulesEnabled)related?.remove();
  function drawer(open){document.body.classList.toggle('nav-drawer-open',open);navButton.setAttribute('aria-expanded',String(open));nav.setAttribute('aria-hidden',String(!open));scrim.hidden=!open;}
  const triggers=()=>[...document.querySelectorAll('[data-term]')];
  function showTerm(trigger){const id=trigger?.dataset.term;if(!id||!trigger.dataset.termSummary)return;opener=trigger;title.textContent=trigger.dataset.termTitle||trigger.textContent.trim();summary.textContent=trigger.dataset.termSummary;full.href=`../../../glossary/index.html#${encodeURIComponent(id)}`;const path=trigger.dataset.mobileRulePath||trigger.dataset.fullRulePath;rule.hidden=!path;if(path){const destination=new URL(window.WHGlossaryReturn.href(path));if(trigger.dataset.mobileRulePath)destination.search=location.search;rule.href=destination.href;}if(!dialog.open)dialog.showModal();}
  function save(mode){if(!opener)return;window.WHGlossaryReturn.save({termId:opener.dataset.term,triggerIndex:triggers().indexOf(opener)});window.WHGlossaryReturn.setRestoreMode(mode);}
  function restore(record){const all=triggers(),trigger=all[record.triggerIndex]?.dataset.term===record.termId?all[record.triggerIndex]:all.find(node=>node.dataset.term===record.termId);history.replaceState(history.state,'',record.path);scrollTo(record.scrollX||0,record.scrollY||0);requestAnimationFrame(()=>{if(trigger)showTerm(trigger);window.WHGlossaryReturn.clear();returnPopup.hidden=true;});}
  function syncReturn(){const record=window.WHGlossaryReturn.read();returnPopup.hidden=!record||window.WHGlossaryReturn.shouldRestoreAutomatically(record);if(record)returnPopup.href=record.path;return record;}
  function filter(){
    if(!relatedRulesEnabled||!loaded||!unit)return;const allowed=new Map(compatibleRuntime.getCompatibleRules(compatibleMatrix,unit.id,{detachmentId:select.value}).filter(item=>!rosterId||item.kind!=='enhancement'||assignedEnhancementRuleIds.has(item.ruleId)).map(item=>[item.ruleId,item]));
    content.querySelectorAll('.stratagem,.enhancement').forEach(card=>{const result=allowed.get(card.dataset.ruleId||card.id);card.hidden=!result;card.dataset.matchState=result?.state||'no-match';card.querySelector(':scope > .compatibility-status')?.remove();if(result?.state==='conditional'){const status=document.createElement('p');status.className='compatibility-status';status.innerHTML='<strong>Conditionally compatible</strong>';for(const condition of compatibleRuntime.conditionsFor(result)){const line=document.createElement('span');line.textContent=compatibleRuntime.conditionLabels[condition]||'Check the full card conditions';status.append(line);}card.prepend(status);}});
    const enhancementTab=related.querySelector('[data-related-tab="enhancements"]'),hasEnhancements=[...content.querySelectorAll('.enhancement')].some(card=>!card.hidden);if(enhancementTab)enhancementTab.hidden=!hasEnhancements;if(kind==='enhancements'&&!hasEnhancements)kind='stratagems';content.querySelectorAll('[data-related-kind]').forEach(group=>group.hidden=group.dataset.relatedKind!==kind||![...group.querySelectorAll('.stratagem,.enhancement')].some(card=>!card.hidden));content.querySelectorAll('.related-detachment').forEach(section=>section.hidden=!(section.dataset.detachment==='core'||select.value==='all'||section.dataset.detachment===select.value)||![...section.querySelectorAll('[data-related-kind]')].some(group=>!group.hidden));related.querySelectorAll('[data-related-tab]').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.relatedTab===kind)));
  }
  async function load(){
    if(!relatedRulesEnabled||loaded)return;try{const [response,matrix]=await Promise.all([fetch('./related-rules.inc?v=2'),compatibleRuntime.loadCompatibleRules(new URL('../generated/compatible-rules.json',scriptUrl))]);if(!response.ok)throw new Error(`HTTP ${response.status}`);content.innerHTML=await response.text();compatibleMatrix=matrix;
      if(rosterId){if(!rosterValid)throw new Error('Roster data unavailable');const entry=selected.get(normalize(unit.dataset.unitTitle)),ownerIds=new Set((entry?.units||[]).map(item=>item.id));assignedEnhancementRuleIds=new Set([...content.querySelectorAll('.enhancement[data-enhancement-title]')].filter(card=>(roster.enhancements||[]).some(item=>item.ownerStatus==='resolved'&&ownerIds.has(item.ownerUnitId)&&normalize(item.name)===normalize(card.dataset.enhancementTitle))).map(card=>card.dataset.ruleId||card.id));content.querySelectorAll('.related-detachment:not(.related-core)').forEach(section=>{if(!rosterDetachments.has(section.dataset.detachment))section.remove();});select.querySelectorAll('option').forEach(option=>{if(option.value==='all'||!rosterDetachments.has(option.value))option.remove();});if(!select.options.length)throw new Error('Roster data unavailable');select.value=select.options[0].value;select.disabled=select.options.length===1;}
      loaded=true;filter();
    }catch(error){console.warn(error);relatedRulesEnabled=false;related?.remove();}
  }
  document.addEventListener('click',event=>{const trigger=event.target.closest('[data-term]');if(trigger){event.preventDefault();showTerm(trigger);}});navButton.addEventListener('click',()=>drawer(!document.body.classList.contains('nav-drawer-open')));scrim.addEventListener('click',()=>drawer(false));dialog.addEventListener('click',event=>{if(event.target===dialog)dialog.close();});full.addEventListener('click',()=>save('automatic'));rule.addEventListener('click',()=>{save('manual');dialog.close();setTimeout(syncReturn,0);});returnPopup.addEventListener('click',event=>{const record=window.WHGlossaryReturn.read();if(!record)return;if(window.WHGlossaryReturn.isSameDocument(record)){event.preventDefault();restore(record);}else window.WHGlossaryReturn.setRestoreMode('automatic');});
  if(relatedRulesEnabled){select?.addEventListener('change',filter);related?.addEventListener('click',event=>{const tab=event.target.closest('[data-related-tab]');if(tab){kind=tab.dataset.relatedTab;filter();}});if(related){if('IntersectionObserver'in window){const observer=new IntersectionObserver(entries=>{if(entries.some(entry=>entry.isIntersecting)){observer.disconnect();load();}},{rootMargin:'600px'});observer.observe(related);}else load();}}
  window.WHPageState?.installTermDialog({dialog,triggers,opener:()=>opener,open:showTerm});const record=window.WHGlossaryReturn.read();if(window.WHGlossaryReturn.shouldRestoreAutomatically(record))requestAnimationFrame(()=>restore(record));else syncReturn();
}());
