import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8'),json=file=>JSON.parse(read(file));
const codex=json('content/space-marines-codex-datasheets.en.json'),details=json('content/space-marines-codex-wargear.en.json'),pack=json('content/space-marines-faction-pack.en.json'),overlay=json('content/space-marines-current-overlay.en.json'),matrix=json('generated/compatible-rules.json'),manifest=json('sources/source-manifest.json'),reader=read('reader.html'),related=read('mobile/related-rules.inc');
const detachments=[...pack.detachments,...overlay.detachments],stratagems=detachments.flatMap(item=>item.stratagems||[]),enhancements=detachments.flatMap(item=>item.enhancements||[]),rows=Object.values(matrix.units).flat();
assert.equal(codex.datasheets.length,101);assert.equal(details.units.length,101);assert.equal(new Set(details.units.map(item=>item.title)).size,101);assert.ok(details.units.every(item=>item.composition));
assert.equal(detachments.length,23);assert.equal(stratagems.length,123);assert.equal(enhancements.length,87);assert.equal(Object.keys(matrix.units).length,101);assert.equal(manifest.gates.publishAsComplete,false);
const renderedRules=new Set([...related.matchAll(/(?:data-rule-id|id)="([^"]+)"/g)].map(match=>match[1]));assert.ok(rows.every(row=>renderedRules.has(row.ruleId)));assert.ok(stratagems.every(rule=>renderedRules.has(rule.id)));
for(const source of details.units){const id=codex.datasheets.find(item=>item.title===source.title)?.id;assert.ok(id,`Missing Datasheet ${source.title}`);const phone=read(`mobile/${id.slice(5)}.html`);for(const line of source.composition.split('\n')){assert.ok(reader.includes(line),`${source.title}: Desktop composition`);assert.ok(phone.includes(line),`${source.title}: Phone composition`);}for(const option of source.wargear){assert.ok(reader.includes(option),`${source.title}: Desktop Wargear Option`);assert.ok(phone.includes(option),`${source.title}: Phone Wargear Option`);}}
const intercessor=details.units.find(item=>item.title==='Intercessor Squad');assert.equal(intercessor.composition,'1 Intercessor Sergeant\n4-9 Intercessors\nEvery model is equipped with: bolt pistol; bolt rifle; close combat weapon.');assert.ok(intercessor.wargear.some(item=>item.includes('Astartes grenade launcher')));assert.match(reader,/unit-intercessor-squad[\s\S]*?Wargear Options/);assert.match(read('mobile/intercessor-squad.html'),/Wargear Options/);
const wargearAbilities=codex.datasheets.filter(item=>item.wargearAbilities?.length),leaders=codex.datasheets.filter(item=>item.relations?.leader?.length),transports=codex.datasheets.filter(item=>item.abilities?.some(ability=>ability.title==='Transport'));assert.equal(leaders.length,26);assert.equal(transports.length,10);
console.log(`Space Marines QA passed: 101 Datasheets, ${details.units.filter(item=>item.wargear.length).length} with Wargear Options, ${wargearAbilities.length} with Wargear Abilities, ${leaders.length} Leaders, ${transports.length} Transports, ${rows.length} Compatible Rules rows.`);
