import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..'),read=file=>fs.readFileSync(path.join(root,file),'utf8'),json=file=>JSON.parse(read(file));
const codex=json('content/space-marines-codex-datasheets.en.json'),details=json('content/space-marines-codex-wargear.en.json'),pack=json('content/space-marines-faction-pack.en.json'),overlay=json('content/space-marines-current-overlay.en.json'),mfm=json('sources/official-mfm-v1.2.json'),matrix=json('generated/compatible-rules.json'),manifest=json('sources/source-manifest.json'),reader=read('reader.html'),targetData=read('scripts/target-data.js'),related=read('mobile/related-rules.inc');
const detachments=[...pack.detachments,...overlay.detachments],stratagems=detachments.flatMap(item=>item.stratagems||[]),enhancements=detachments.flatMap(item=>item.enhancements||[]),rows=Object.values(matrix.units).flat();
assert.equal(codex.datasheets.length,101);assert.equal(details.units.length,101);assert.equal(new Set(details.units.map(item=>item.title)).size,101);assert.ok(details.units.every(item=>item.composition));
assert.equal(detachments.length,23);assert.equal(stratagems.length,123);assert.equal(enhancements.length,87);assert.equal(Object.keys(matrix.units).length,101);assert.equal(manifest.gates.publishAsComplete,false);
const currentPack=manifest.layers.find(item=>item.id==='faction-pack-v1.1'),packBinary=fs.readFileSync(path.join(root,'sources/space-marines-faction-pack-v1.1.pdf'));
assert.equal(pack.meta.version,'1.1');assert.equal(pack.meta.pageCount,219);assert.equal(pack.meta.sha256,'A9F2AB0A28AA1E4ED649667ADDE34C4B2C185A4493C070CEF9768C61FC9B93A6');assert.equal(crypto.createHash('sha256').update(packBinary).digest('hex').toUpperCase(),pack.meta.sha256);assert.equal(currentPack.sha256,pack.meta.sha256);assert.equal(currentPack.pageCount,219);
assert.equal(pack.detachments.length,16);assert.equal(overlay.detachments.length,7);assert.ok(pack.detachments.some(item=>item.title==='Vengeful Hosts'));assert.ok(!overlay.detachments.some(item=>item.title==='Vengeful Hosts'));assert.equal(pack.datasheets.matched.length,14);assert.equal(pack.datasheets.imperialArmour.length,2);assert.equal(pack.datasheets.legends.length,76);assert.equal(pack.updates.length,5);assert.equal(pack.faqs.length,14);
const fulguris=pack.detachments.find(item=>item.title==='Fulguris Task Force');assert.deepEqual(fulguris.enhancements.map(item=>[item.title,item.kind]),[['Bellicose Weapon Spirits (Upgrade)','Upgrade'],['Raptorial Cogitator Core (Upgrade)','Upgrade']]);
assert.equal(mfm.version,'v1.2');assert.equal(mfm.verifiedUnits.length,103);assert.equal(mfm.detachments.length,23);assert.equal(mfm.enhancements.length,87);const outrider=mfm.unitOverrides.find(item=>item.title==='OUTRIDER SQUAD');assert.deepEqual(outrider.paidWargear,[{name:'Invader ATV',value:60,modifiers:[]}]);assert.match(reader,/11E · Space Marines reference/);assert.match(targetData,/Official Faction Pack v1\.1/);
const renderedRules=new Set([...related.matchAll(/(?:data-rule-id|id)="([^"]+)"/g)].map(match=>match[1]));assert.ok(rows.every(row=>renderedRules.has(row.ruleId)));assert.ok(stratagems.every(rule=>renderedRules.has(rule.id)));
for(const source of details.units){const id=codex.datasheets.find(item=>item.title===source.title)?.id;assert.ok(id,`Missing Datasheet ${source.title}`);const stub=read(`mobile/${id.slice(5)}.html`);assert.match(stub,new RegExp(`data-canonical-target="${id}"`));assert.doesNotMatch(stub,/<(?:article|section)\b|class="[^"]*\bunit-card\b|data-rule-id=/);for(const line of source.composition.split('\n'))assert.ok(targetData.includes(line),`${source.title}: canonical composition`);for(const option of source.wargear)assert.ok(targetData.includes(JSON.stringify(option).slice(1,-1)),`${source.title}: canonical Wargear Option`);}
const intercessor=details.units.find(item=>item.title==='Intercessor Squad');assert.equal(intercessor.composition,'1 Intercessor Sergeant\n4-9 Intercessors\nEvery model is equipped with: bolt pistol; bolt rifle; close combat weapon.');assert.ok(intercessor.wargear.some(item=>item.includes('Astartes grenade launcher')));assert.match(targetData,/unit-intercessor-squad[\s\S]*?Wargear Options/);assert.match(read('mobile/intercessor-squad.html'),/data-canonical-target="unit-intercessor-squad"/);
const intercessorData=codex.datasheets.find(item=>item.title==='Intercessor Squad'),intercessorAbilities=intercessorData.abilities.map(item=>item.title);assert.deepEqual(intercessorAbilities,['Objective Secured','Hail of Bolts','Oath of Moment']);
const intercessorWeaponTags=intercessorData.weapons.flatMap(item=>item.abilities.split(',').map(value=>value.trim()).filter(Boolean));for(const tag of ['Assault','Heavy','Blast','Pistol','Ignores Cover','Torrent','Hazardous','Devastating Wounds','Close-Quarters'])assert.ok(intercessorWeaponTags.includes(tag),`Intercessor weapon tag ${tag}`);
assert.ok(codex.datasheets.find(item=>item.title==='Terminator Squad').abilities.some(item=>item.title==='Deep Strike'));assert.ok(codex.datasheets.find(item=>item.title==='Redemptor Dreadnought').abilities.some(item=>item.title.startsWith('Deadly Demise')));assert.ok(codex.datasheets.some(item=>item.relations?.leader?.length));
const wargearAbilities=codex.datasheets.filter(item=>item.wargearAbilities?.length),leaders=codex.datasheets.filter(item=>item.relations?.leader?.length),transports=codex.datasheets.filter(item=>item.abilities?.some(ability=>ability.title==='Transport'));assert.equal(leaders.length,26);assert.equal(transports.length,10);
assert.equal(wargearAbilities.reduce((sum,item)=>sum+item.wargearAbilities.length,0),17);
console.log(`Space Marines QA passed: 101 Datasheets, ${details.units.filter(item=>item.wargear.length).length} with Wargear Options, ${wargearAbilities.length} with Wargear Abilities, ${leaders.length} Leaders, ${transports.length} Transports, ${rows.length} Compatible Rules rows.`);
