(async function(){
  'use strict';
  const scriptUrl=document.currentScript.src,runtime=await import(new URL('./compatible-rules-runtime.mjs?v=1',scriptUrl)),matrix=await runtime.loadCompatibleRules(new URL('../generated/compatible-rules.json',scriptUrl));let templatePromise;
  const template=()=>templatePromise||(templatePromise=fetch('./mobile/related-rules.inc?v=4').then(response=>{if(!response.ok)throw new Error(`HTTP ${response.status}`);return response.text();}).then(html=>{const node=document.createElement('template');node.innerHTML=html;return node;}));
  function install(){
    const layer=document.createElement('div');layer.className='related-rules-layer';layer.hidden=true;layer.innerHTML='<section class="related-rules-dialog" role="dialog" aria-modal="true" aria-labelledby="relatedRulesTitle"><header><div><span>Datasheet tools</span><h2 id="relatedRulesTitle">Compatible Stratagems &amp; Enhancements</h2></div><button type="button" class="related-rules-close" aria-label="Close">&times;</button></header><div class="related-rules-body"><p>Loading rules&hellip;</p></div></section>';document.body.append(layer);
    const body=layer.querySelector('.related-rules-body'),title=layer.querySelector('h2'),rosterMode=Boolean(window.SM_ROSTER_GUIDE);let unit,kind='stratagems',detachment='all',filterMenu,tabs,content,empty,sections,modal;
    const filter=()=>{const assigned=new Set(window.SM_ROSTER_GUIDE?.enhancementRuleIdsByUnitId?.[unit.id]||[]),compatible=runtime.getCompatibleRules(matrix,unit.id,{detachmentId:detachment}),presented=rosterMode?compatible:window.WHRuleFacts.filterStaticCompatible(compatible),rules=rosterMode?presented.filter(rule=>rule.kind!=='enhancement'||assigned.has(rule.ruleId)):presented,byId=new Map(rules.map(rule=>[rule.ruleId,rule])),hasEnhancements=rules.some(rule=>rule.kind==='enhancement');if(kind==='enhancements'&&!hasEnhancements)kind='stratagems';tabs.querySelector('[data-kind="enhancements"]').hidden=!hasEnhancements;title.textContent=`${unit.querySelector('.unit-name')?.textContent.trim()||'Datasheet'} · ${hasEnhancements?'Compatible Stratagems & Enhancements':'Compatible Stratagems'}`;content.querySelectorAll('.stratagem,.enhancement').forEach(card=>{const result=byId.get(card.dataset.ruleId);card.hidden=!result;card.querySelector(':scope > .compatibility-status')?.remove();if(result?.state==='conditional'){const status=document.createElement('p');status.className='compatibility-status';status.innerHTML='<strong>Conditionally compatible</strong><span>Check the full card conditions</span>';card.prepend(status);}});content.querySelectorAll('[data-related-kind]').forEach(group=>group.hidden=group.dataset.relatedKind!==kind||![...group.querySelectorAll('.stratagem,.enhancement')].some(card=>!card.hidden));sections.forEach(section=>section.hidden=!(section.dataset.detachment==='core'||detachment==='all'||section.dataset.detachment===detachment)||![...section.querySelectorAll('[data-related-kind]')].some(group=>!group.hidden));tabs.querySelectorAll('button').forEach(button=>button.setAttribute('aria-pressed',String(button.dataset.kind===kind)));empty.hidden=sections.some(section=>!section.hidden);};
    const close=()=>{if(layer.hidden)return;layer.hidden=true;document.documentElement.classList.remove('related-rules-open');modal.deactivate();};modal=window.WHModalFocus.create(layer,close);layer.addEventListener('click',event=>{if(event.target===layer||event.target.closest('.related-rules-close'))close();const tab=event.target.closest('[data-kind]');if(tab){kind=tab.dataset.kind;filter();}});
    async function open(current,state={}){unit=current;kind=state.kind||'stratagems';layer.hidden=false;document.documentElement.classList.add('related-rules-open');modal.activate(current.querySelector('.related-rules-trigger'));if(!content){const source=await template(),fragment=source.content.cloneNode(true);fragment.querySelectorAll('[id]').forEach(node=>{node.dataset.ruleId=node.id;node.removeAttribute('id');});sections=[...fragment.querySelectorAll('.related-detachment')];const choices=[['all','All Detachments'],...sections.filter(section=>section.dataset.detachment!=='core').map(section=>[section.dataset.detachment,section.querySelector('h2').textContent])];filterMenu=document.createElement('details');filterMenu.className='full-related-filter';filterMenu.innerHTML='<summary><span>All Detachments</span></summary><div>'+choices.map(([value,label])=>`<button type="button" data-detachment="${value}">${label}</button>`).join('')+'</div>';tabs=document.createElement('div');tabs.className='full-related-tabs';tabs.innerHTML='<button type="button" data-kind="stratagems" aria-pressed="true">Stratagems</button><button type="button" data-kind="enhancements" aria-pressed="false">Enhancements</button>';const controls=document.createElement('div');controls.className='full-related-controls';controls.append(filterMenu,tabs);content=document.createElement('div');content.className='full-related-content';content.append(fragment);empty=document.createElement('p');empty.className='full-related-empty';body.replaceChildren(controls,content,empty);filterMenu.addEventListener('click',event=>{const button=event.target.closest('[data-detachment]');if(!button)return;detachment=button.dataset.detachment;filterMenu.querySelector('summary span').textContent=button.textContent;filterMenu.open=false;filter();});}if(state.detachment)detachment=state.detachment;filter();modal.focusFirst();}
    document.querySelectorAll('.unit-card').forEach(current=>{if(!(matrix.units[current.id]||[]).length)return;const keywords=[...current.querySelectorAll('.unit-part')].find(part=>part.id.endsWith('-keywords'));if(!keywords)return;const button=document.createElement('button');button.type='button';button.className='related-rules-trigger';button.textContent='Compatible Stratagems & Enhancements';button.addEventListener('click',()=>open(current));keywords.after(button);});
    return{layer,close,snapshot(){return layer.hidden?null:{type:'related-rules',unitId:unit?.id||'',detachment,kind};},async restore(state){const restored=document.getElementById(state?.unitId);if(!restored)return null;await open(restored,state);return restored.querySelector('.related-rules-trigger');}};
  }
  window.WHArmyRelatedRules=Object.freeze({install});window.WHArmyBook.install({bookId:'space-marines',readerPath:'./reader.html',dedicatedMobile:true});
}()).catch(error=>{document.documentElement.dataset.bookError=String(error?.stack||error);console.error(error);});
