import assert from 'node:assert/strict';
import fs from 'node:fs';

const read=file=>JSON.parse(fs.readFileSync(new URL(file,import.meta.url),'utf8'));
const text=file=>fs.readFileSync(new URL(file,import.meta.url),'utf8');
const config=read('../book.config.json'),codex=read('../content/blood-angels-codex-datasheets.en.json'),pack=read('../content/blood-angels-faction-pack.en.json'),parity=read('../content/blood-angels-codex-parity.en.json'),manifest=read('../sources/source-manifest.json'),spaceMarines=read('../../space-marines/content/space-marines-codex-datasheets.en.json');
const excluded=new Set(config.dependencyDatasheets.excludeAnyKeywords.map(value=>value.toUpperCase()));
const shared=spaceMarines.datasheets.filter(unit=>!(unit.keywords||[]).some(item=>excluded.has(String(item).toUpperCase()))),localIds=new Set(codex.datasheets.map(unit=>unit.id));

assert.equal(config.id,'blood-angels');
assert.deepEqual(config.dependencies,['space-marines']);
assert.equal(config.dependencyDatasheets.groupByBook,false);
assert.equal(config.rosterSupport,true);
assert.equal(config.compatibleRulesMatrix,true);
assert.equal(config.expected.matchedDetachments,8);
assert.equal(config.expected.codexDatasheets,15);
assert.equal(codex.datasheets.length,15);
assert.equal(shared.length,82);
assert.equal(shared.filter(unit=>localIds.has(unit.id)).length,0);
assert.equal((pack.detachments||[]).length+(parity.detachments||[]).length,8);
assert.equal(manifest.gates?.publishAsComplete,false);
assert.equal(Boolean(config.coverImage&&config.entryCoverImage),true,'Blood Angels cover artwork must be configured');
assert.equal(codex.datasheets.some(unit=>Boolean(unit.image||unit.imagePath||unit.headerArt||unit.headerArtMode)),false,'Blood Angels datasheet images must remain absent');

const reader=text('../reader.html');
const units=new Map(codex.datasheets.map(unit=>[unit.title,unit]));
const ability=(unit,title)=>units.get(unit).abilities.find(item=>item.title===title)?.text||'';
assert.equal((reader.match(/<article class="unit-card/g)||[]).length,97);
assert.equal((reader.match(/Space Marines shared datasheet/g)||[]).length,82);
assert.doesNotMatch(reader,/data-nav-id="datasheets-(?:blood-angels|space-marines)"/);
assert.match(reader,/scripts\/roster-filter\.js\?v=1/);
const app=text('../scripts/app.js');
assert.match(app,/generated\/compatible-rules\.json/);
assert.match(app,/location\.hash\.slice\(1\)/,'Desktop to Phone switching must prefer the current semantic hash');
for(const unit of spaceMarines.datasheets.filter(item=>!shared.includes(item)))assert.ok(!reader.includes(`id="${unit.id}"`),`${unit.title} leaked into Blood Angels`);
assert.match(ability('Death Company Dreadnought','Driven by Fury'),/surge move of up to D6\+2"/);
assert.match(ability('Death Company Marines with Bolt Rifles','Visions of Heresy'),/re-roll Charge rolls[\s\S]*Heroic Intervention stratagem[\s\S]*‑1 CP/);
assert.match(ability('The Sanguinor','Miraculous Saviour'),/excluding the first battle round[\s\S]*ingress move[\s\S]*eligible to move/);
for(const title of ['Death Company Captain','Death Company Captain with Jump Pack','Death Company Marines','Death Company Marines with Bolt Rifles','Death Company Marines with Jump Packs','Death Company Dreadnought'])assert.doesNotMatch(ability(title,'Black Rage'),/[’']$/);
assert.equal(units.get('Death Company Captain').weapons.find(item=>item.name==='Heavy Bolt Pistol').abilities,'Pistol');
assert.equal(units.get('Death Company Captain with Jump Pack').weapons.find(item=>item.name.includes('Plasma pistol - standard')).skill,'2+');
assert.equal(units.get('Death Company Marines with Bolt Rifles').weapons.filter(item=>item.name.toLowerCase()==='close combat weapon').length,1);
assert.equal(units.get('Death Company Marines with Bolt Rifles').weapons.find(item=>item.name==='Bolt pistol').abilities,'Pistol');
for(const [title,keyword] of [['Astorath','Tacticus'],['Chief Librarian Mephiston','Imperium'],['Lemartes','Tacticus'],['The Sanguinor','Tacticus'],['Sanguinary Guard','Tacticus']])assert.ok(units.get(title).keywords.includes(keyword),`${title} must include ${keyword}`);
for(const [title,max] of [['Death Company Marines',10],['Death Company Marines with Bolt Rifles',10],['Death Company Marines with Jump Packs',10],['Sanguinary Guard',6]])assert.equal(Math.max(...units.get(title).points.map(item=>item.maxModels)),max,`${title} point schedule upper size`);
for(const id of ['liberator-assault-group','the-lost-brethren','the-angelic-host'])assert.match(parity.detachments.find(item=>item.id===id).rule.text,/cannot include any ADEPTUS ASTARTES units drawn from any other Chapter/);
assert.match(parity.detachments.find(item=>item.id==='the-lost-brethren').rule.text,/BATTLELINE[\s\S]*DOOMED/);
assert.equal(parity.detachments.flatMap(item=>item.stratagems).filter(item=>item.typeStatus==='confirmed'&&item.sourceLabel===item.canonicalType).length,18);
assert.match(reader,/id="sanguinary-priest-support"[\s\S]*<h4>Support<\/h4>/);
const priestStart=reader.indexOf('<article class="unit-card surface" id="unit-sanguinary-priest"');
const priestReader=reader.slice(priestStart,reader.indexOf('<article class="unit-card surface"',priestStart+1));
assert.equal((priestReader.match(/data-source-field="abilities\.support"/g)||[]).length,1,'relation Support card must not duplicate the Core Support ability');
assert.match(reader,/1 hand flamer and 1 Astartes chainsword[\s\S]*1 plasma pistol and 1 power weapon/);
assert.match(reader,/SECONDARY CODEX/);
assert.doesNotMatch(reader,/Carmine Reliquary[\s\S]{0,900}result\.\./);
console.log('Blood Angels QA passed: 15 local + 82 shared Datasheets, 8 Detachments, unified navigation, roster and Compatible Rules enabled.');
