import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';

const read=file=>JSON.parse(fs.readFileSync(new URL(file,import.meta.url),'utf8')),text=file=>fs.readFileSync(new URL(file,import.meta.url),'utf8');
const config=read('../book.config.json'),codex=read('../content/blood-angels-codex-datasheets.en.json'),pack=read('../content/blood-angels-faction-pack.en.json'),parity=read('../content/blood-angels-codex-parity.en.json'),manifest=read('../sources/source-manifest.json'),reader=text('../reader.html');
const context={window:{}};vm.createContext(context);for(const file of ['../scripts/roster-data.js','../scripts/target-data.js'])vm.runInContext(text(file),context);const catalog=context.window.WH_BOOK_ROSTER_CATALOG;
assert.equal(config.id,'blood-angels');assert.deepEqual(config.dependencies,['space-marines']);assert.equal(config.rosterSupport,true);assert.equal(config.sharedArmyBookApp,true);assert.equal(config.compatibleRulesMatrix,true);
assert.equal(codex.datasheets.length,15);assert.equal(catalog.units.length,97);assert.equal(catalog.units.filter(unit=>unit.sourceBookId==='space-marines').length,82);assert.equal(catalog.units.filter(unit=>unit.sourceBookId==='blood-angels').length,15);assert.equal(catalog.detachments.length,24);assert.equal(catalog.detachments.filter(item=>item.sourceBookId==='blood-angels').length,8);
assert.equal((pack.detachments||[]).length+(parity.detachments||[]).length,8);assert.equal(manifest.gates?.publishAsComplete,false);assert.equal(Boolean(config.coverImage&&config.entryCoverImage),true);assert.equal(codex.datasheets.some(unit=>Boolean(unit.image||unit.imagePath||unit.headerArt||unit.headerArtMode)),false);
assert.equal((reader.match(/data-nav-id="detachment-[^"]+"/g)||[]).length,24);assert.equal((reader.match(/data-nav-id="unit-[^"]+"/g)||[]).length,97);assert.match(reader,/scripts\/roster-data\.js\?v=/);assert.match(reader,/shared\/army-book-app\.js\?v=/);assert.doesNotMatch(reader,/data-nav-id="datasheets-(?:blood-angels|space-marines)"/);
const units=new Map(codex.datasheets.map(unit=>[unit.title,unit])),ability=(unit,title)=>units.get(unit).abilities.find(item=>item.title===title)?.text||'';
assert.match(ability('Death Company Dreadnought','Driven by Fury'),/surge move of up to D6\+2"/);assert.match(ability('Death Company Marines with Bolt Rifles','Visions of Heresy'),/re-roll Charge rolls[\s\S]*Heroic Intervention stratagem[\s\S]*1 CP/);assert.match(ability('The Sanguinor','Miraculous Saviour'),/excluding the first battle round[\s\S]*ingress move/);
for(const title of ['Death Company Captain','Death Company Captain with Jump Pack','Death Company Marines','Death Company Marines with Bolt Rifles','Death Company Marines with Jump Packs','Death Company Dreadnought'])assert.doesNotMatch(ability(title,'Black Rage'),/[’']$/);
for(const id of ['liberator-assault-group','the-lost-brethren','the-angelic-host'])assert.match(parity.detachments.find(item=>item.id===id).rule.text,/cannot include any ADEPTUS ASTARTES units drawn from any other Chapter/i);
assert.match(parity.detachments.find(item=>item.id==='the-lost-brethren').rule.text,/BATTLELINE[\s\S]*DOOMED/);assert.ok(parity.armyRules.some(item=>item.id==='army-rule-the-sons-of-sanguinius'));assert.match(JSON.stringify(context.window.WH_ARMY_BOOK_TARGETS.html),/SPACE MARINES SHARED/);
console.log('Blood Angels QA passed: 15 local + 82 inherited Datasheets, 8 local + 16 shared Detachments and dynamic generated-reader wiring.');
