(function(root){
  'use strict';
  const normalize=value=>root.WHRosterParser?.normalize(value)||String(value||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim(),list=value=>Array.isArray(value)?value:[];
  const ABILITY=Object.freeze({perfectionists:'emperors-children-ability-perfectionists',lordHost:'emperors-children-ability-lord-of-the-host',annunciation:'emperors-children-ability-obsessive-annunciation',interference:'emperors-children-ability-warped-interference-psychic'});
  const ENHANCEMENT=Object.freeze({tears:'tears-of-the-phoenix',exalted:'exalted-patron',spiritsliver:'spiritsliver',cacophonic:'cacophonic-accompaniment',ferocity:'frenzied-ferocity',crown:'euphoric-crown',plate:'howling-plate',distortion:'enhancement-distortion',eagerPatrons:'eager-patrons',steeped:'enhancement-steeped-in-suffering',musk:'enhancement-intoxicating-musk',loathsome:'enhancement-loathsome-dexterity',faultless:'enhancement-faultless-opportunist',blinding:'enhancement-blinding-speed',spearhead:'enhancement-spearhead-striker',empyric:'enhancement-empyric-suffusion',warpWalker:'enhancement-warp-walker',darkGlory:'enhancement-pledge-of-dark-glory',unholyFortune:'enhancement-pledge-of-unholy-fortune',eagerProve:'enhancement-eager-to-prove',repulsed:'enhancement-repulsed-by-weakness',proud:'enhancement-proud-and-vainglorious',slayer:'enhancement-slayer-of-champions'});
  const DETACHMENT_RULE=Object.freeze({carnival:'emperors-children-detachment-rule-daemonic-empowerment',coterie:'emperors-children-detachment-rule-pledges-to-the-dark-prince',court:'emperors-children-detachment-rule-sensational-performance',elegant:'emperors-children-detachment-rule-eager-to-kill',frenzied:'emperors-children-detachment-rule-frantic-focus',mercurial:'emperors-children-detachment-rule-quicksilver-grace',peerless:'emperors-children-detachment-rule-exquisite-swordsmanship',rapid:'emperors-children-detachment-rule-mechanised-murder',chosen:'emperors-children-detachment-rule-internal-rivalries',spectacle:'emperors-children-detachment-rule-entitled-to-victory'});
  const UNIT=Object.freeze({exultant:'unit-lord-exultant',kakophonist:'unit-lord-kakophonist',sorcerer:'unit-sorcerer',terminators:'unit-chaos-terminators',flawless:'unit-flawless-blades'});
  const detachmentId=value=>normalize(value).replace(/^detachment /,'').replace(/ /g,'-'),canonicalId=draft=>draft?.identity?.canonicalDatasheetId||draft?.item?.catalogUnit?.id||'';
  const keywordValues=profile=>{const removed=new Set(list(profile?.removed).map(item=>normalize(item?.title||item)));return[...new Set([...list(profile?.effective),...list(profile?.intrinsic),...list(profile?.added)].map(item=>item?.title||item).filter(item=>item&&!removed.has(normalize(item))))];},keyword=(draft,value)=>keywordValues(draft?.rosterState?.keywordProfile).some(item=>normalize(item)===normalize(value));
  const attachedGroup=(draft,byInstance)=>{let bodyguard=draft;if(list(draft?.attachments?.leading).length)bodyguard=byInstance.get(draft.attachments.leading[0].instanceId);if(!bodyguard||!list(bodyguard.attachments?.leaders).length)return null;return[bodyguard,...bodyguard.attachments.leaders.map(item=>byInstance.get(item.instanceId)).filter(Boolean)];};
  const ownerResolution=(enhancements,id)=>list(enhancements).find(item=>item?.input?.ownerStatus==='resolved'&&item?.catalog?.id===id),selectedWargear=(draft,title)=>{const ids=new Set(list(draft?.selection?.loadout?.selectedWargearAbilityIds));return list(draft?.item?.catalogUnit?.gameSelections?.wargearAbilities).find(ability=>ids.has(ability.id)&&normalize(ability.title)===normalize(title))||null;};
  const source=(kind,id,ownerInstanceId=null,rosterFact=kind)=>({source:{kind,id,ownerInstanceId},provenance:{rosterFact}}),effect=(id,component,targetId,operation,detail={},origin={})=>({id,component,targetId,operation,...detail,...origin}),reference=(kind,id,origin)=>effect(`canonical-${id}`,'ability',id,'reference',{canonicalReference:{kind,id},...(kind==='ability'?{canonicalAbilityId:id}:{}),state:'reference'},origin),stat=(id,targetId,operation,value,origin)=>effect(id,'stat',targetId,operation,operation==='add'?{delta:value}:{to:value},origin),weapon=(id,targetId,operation,detail,origin)=>effect(id,'weapon',targetId,operation,detail,origin),ability=(id,targetId,title,origin)=>effect(id,'ability',targetId,'grant',{title},origin);
  const projectEffects=context=>{
    const {gameUnit:draft,byInstance,enhancements}=context,output=[],group=attachedGroup(draft,byInstance),bodyguard=group?.[0]||null,leaders=group?group.slice(1):[],cardId=canonicalId(draft),leader=id=>leaders.find(item=>canonicalId(item)===id)||null,attachmentOrigin=(id,owner)=>source('explicit-attachment',id,owner.identity.instanceId,'explicit-attachment'),bodyReference=(kind,id,owner)=>{if(bodyguard&&draft===bodyguard)output.push(reference(kind,id,attachmentOrigin(id,owner)));};
    const exultant=leader(UNIT.exultant);if(exultant){output.push(weapon('perfectionists-weapons','all','grant-tag',{tag:'LETHAL HITS',termId:'core-lethal-hits'},attachmentOrigin(ABILITY.perfectionists,exultant)));if(draft===exultant&&keyword(bodyguard,'BATTLELINE')){output.push(ability('lord-host-infiltrators','core-infiltrators','Infiltrators',attachmentOrigin(ABILITY.lordHost,exultant)));output.push(ability('lord-host-scouts','core-scouts','Scouts 6"',attachmentOrigin(ABILITY.lordHost,exultant)));}}
    const kakophonist=leader(UNIT.kakophonist);if(kakophonist)output.push(weapon('obsessive-annunciation','ranged','grant-tag',{tag:'SUSTAINED HITS 1',termId:'core-sustained-hits'},attachmentOrigin(ABILITY.annunciation,kakophonist)));
    const sorcerer=leader(UNIT.sorcerer);if(sorcerer)bodyReference('ability',ABILITY.interference,sorcerer);
    const detachments=new Set(list(draft?.rosterState?.detachments).map(detachmentId)),detachmentOrigin=id=>source('detachment',id,null,'selected-detachment'),ec=keyword(draft,"EMPEROR'S CHILDREN"),characterUnit=keyword(draft,'CHARACTER')||Boolean(group),detachmentReference=(detachment,id,applies=true)=>{if(detachments.has(detachment)&&applies)output.push(reference('detachment-rule',id,detachmentOrigin(detachment)));};
    detachmentReference('carnival-of-excess',DETACHMENT_RULE.carnival,ec||keyword(draft,'LEGIONS OF EXCESS'));detachmentReference('coterie-of-the-conceited',DETACHMENT_RULE.coterie,ec);detachmentReference('court-of-the-phoenician',DETACHMENT_RULE.court,ec);detachmentReference('elegant-brutes',DETACHMENT_RULE.elegant,cardId===UNIT.terminators);detachmentReference('frenzied-host',DETACHMENT_RULE.frenzied,keyword(draft,'BATTLELINE'));detachmentReference('mercurial-host',DETACHMENT_RULE.mercurial,ec);detachmentReference('peerless-bladesmen',DETACHMENT_RULE.peerless,ec);detachmentReference('rapid-evisceration',DETACHMENT_RULE.rapid,ec);detachmentReference('slaaneshs-chosen',DETACHMENT_RULE.chosen,ec&&characterUnit);detachmentReference('spectacle-of-slaughter',DETACHMENT_RULE.spectacle,cardId===UNIT.flawless);
    const enhancementOwner=id=>{const resolution=ownerResolution(enhancements,id),owner=resolution&&byInstance.get(resolution.input.ownerUnitId);return owner||null;},own=id=>{const owner=enhancementOwner(id);return owner===draft?owner:null;},scoped=id=>{const owner=enhancementOwner(id);return owner&&(owner===draft||group?.includes(owner))?owner:null;},enhancementOrigin=(id,owner,attached=false)=>source(attached?'explicit-attachment':'enhancement',id,owner.identity.instanceId,'enhancement-owner'),attachedReference=id=>{const owner=scoped(id);if(owner&&bodyguard&&draft===bodyguard)output.push(reference('enhancement',id,enhancementOrigin(id,owner,true)));return owner;};
    attachedReference(ENHANCEMENT.tears);const exalted=own(ENHANCEMENT.exalted);if(exalted)output.push(stat('exalted-patron-move','M','add',1,enhancementOrigin(ENHANCEMENT.exalted,exalted)));const spiritsliver=own(ENHANCEMENT.spiritsliver);if(spiritsliver){output.push(weapon('spiritsliver-strength','melee','add-stat',{stat:'S',delta:1},enhancementOrigin(ENHANCEMENT.spiritsliver,spiritsliver)));output.push(weapon('spiritsliver-attacks','melee','add-stat',{stat:'A',delta:1},enhancementOrigin(ENHANCEMENT.spiritsliver,spiritsliver)));}
    const cacophonic=scoped(ENHANCEMENT.cacophonic);if(cacophonic){if(draft===cacophonic)output.push(ability('cacophonic-deep-strike','core-deep-strike','Deep Strike',enhancementOrigin(ENHANCEMENT.cacophonic,cacophonic)));output.push(weapon('cacophonic-ignores-cover','ranged','grant-tag',{tag:'IGNORES COVER',termId:'core-ignores-cover'},enhancementOrigin(ENHANCEMENT.cacophonic,cacophonic,draft!==cacophonic)));if(bodyguard&&draft===bodyguard)output.push(reference('enhancement',ENHANCEMENT.cacophonic,enhancementOrigin(ENHANCEMENT.cacophonic,cacophonic,true)));}
    const ferocity=own(ENHANCEMENT.ferocity);if(ferocity)output.push(weapon('frenzied-ferocity','all','grant-tag',{tag:'SUSTAINED HITS 1',termId:'core-sustained-hits'},enhancementOrigin(ENHANCEMENT.ferocity,ferocity)));const crown=own(ENHANCEMENT.crown);if(crown)output.push(weapon('euphoric-crown','melee','add-stat',{stat:'S',delta:1},enhancementOrigin(ENHANCEMENT.crown,crown)));const plate=scoped(ENHANCEMENT.plate);if(plate)output.push(weapon('howling-plate','ranged','add-stat',{stat:'AP',delta:-1},enhancementOrigin(ENHANCEMENT.plate,plate,draft!==plate)));const distortion=own(ENHANCEMENT.distortion);if(distortion){output.push(weapon('distortion-attacks','melee','add-stat',{stat:'A',delta:1},enhancementOrigin(ENHANCEMENT.distortion,distortion)));output.push(weapon('distortion-damage','melee','add-stat',{stat:'D',delta:1},enhancementOrigin(ENHANCEMENT.distortion,distortion)));}const eagerPatrons=own(ENHANCEMENT.eagerPatrons);if(eagerPatrons)output.push(stat('eager-patrons-move','M','add',2,enhancementOrigin(ENHANCEMENT.eagerPatrons,eagerPatrons)));
    attachedReference(ENHANCEMENT.steeped);attachedReference(ENHANCEMENT.musk);attachedReference(ENHANCEMENT.loathsome);attachedReference(ENHANCEMENT.faultless);attachedReference(ENHANCEMENT.blinding);attachedReference(ENHANCEMENT.spearhead);attachedReference(ENHANCEMENT.empyric);attachedReference(ENHANCEMENT.warpWalker);attachedReference(ENHANCEMENT.unholyFortune);attachedReference(ENHANCEMENT.eagerProve);attachedReference(ENHANCEMENT.repulsed);attachedReference(ENHANCEMENT.proud);
    const darkGlory=scoped(ENHANCEMENT.darkGlory);if(darkGlory){output.push(stat('pledge-dark-glory-leadership','Ld','add',-1,enhancementOrigin(ENHANCEMENT.darkGlory,darkGlory,draft!==darkGlory)));output.push(stat('pledge-dark-glory-objective-control','OC','add',1,enhancementOrigin(ENHANCEMENT.darkGlory,darkGlory,draft!==darkGlory)));}const slayer=own(ENHANCEMENT.slayer);if(slayer)output.push(weapon('slayer-of-champions-precision','melee','grant-tag',{tag:'PRECISION',termId:'core-precision'},enhancementOrigin(ENHANCEMENT.slayer,slayer)));
    const icon=selectedWargear(draft,'Daemonic Icon');if(icon)output.push(stat('daemonic-icon-leadership','Ld','set','6+',source('selected-wargear',icon.id,draft.identity.instanceId,'selected-wargear')));const aegis=selectedWargear(draft,'Shining aegis');if(aegis)output.push(stat('shining-aegis-save','Sv','set','3+',source('selected-wargear',aegis.id,draft.identity.instanceId,'selected-wargear')));return output;
  };
  const provider={keywordProfile(context,base){return{...base,effective:keywordValues(base)};},gameEffects:projectEffects,decorate(card,projection,items){root.WHBookRosterEnhancements?.decorate?.(card,projection.roster,items.map(item=>item.raw),{projectedEffects:items[0]?.game?.effects||[]});}},run=()=>{if(!root.WHArmyRosterContext)return false;root.WHArmyRosterContext.install({bookId:'emperors-children',guideGlobal:'EC_ROSTER_GUIDE',provider});return true;};
  root.ECRosterSemantics=Object.freeze({normalize,projectEffects,ABILITY,ENHANCEMENT,DETACHMENT_RULE});if(!run())root.addEventListener('wh-roster-context-ready',run,{once:true});
}(window));
