import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
import {fileURLToPath} from 'node:url';

const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../../..'),json=relative=>JSON.parse(fs.readFileSync(path.join(root,relative),'utf8'));
const datasheets=json('books/tyranids/content/tyranids-codex-datasheets.en.json'),pack=json('books/tyranids/content/tyranids-faction-pack.en.json'),parity=json('books/tyranids/content/tyranids-codex-parity.en.json'),points=json('books/tyranids/content/tyranids-points.en.json');
const scope={window:{}};scope.window.window=scope.window;vm.runInNewContext(fs.readFileSync(path.join(root,'books/tyranids/scripts/target-data.js'),'utf8'),scope);vm.runInNewContext(fs.readFileSync(path.join(root,'books/tyranids/scripts/roster-data.js'),'utf8'),scope);
const targets=scope.window.WH_ARMY_BOOK_TARGETS,catalog=scope.window.WH_BOOK_ROSTER_CATALOG,detachments=[...pack.detachments,...parity.detachments],enhancements=detachments.flatMap(item=>item.enhancements||[]),stratagems=detachments.flatMap(item=>item.stratagems||[]),abilityCount=datasheets.datasheets.reduce((sum,unit)=>sum+(unit.abilities?.length||0),0),weaponCount=datasheets.datasheets.reduce((sum,unit)=>sum+(unit.weapons?.length||0),0),leaders=catalog.units.filter(unit=>unit.relations.canLead.length);
assert.equal(datasheets.datasheets.length,50);
assert.equal(abilityCount,227);
assert.equal(weaponCount,127);
assert.ok(datasheets.datasheets.every(unit=>unit.wargearAbilities.length===0));
assert.equal(detachments.length,10);
assert.equal(enhancements.length,34);
assert.equal(stratagems.length,51);
assert.equal(points.units.length,50);
assert.equal(points.enhancements.length,34);
assert.equal(pack.updates.length,32);
assert.equal(pack.faqs.length,12);
assert.equal(leaders.length,8);
assert.equal(targets.schema,'wh40k-army-book-targets/v1');
assert.equal(targets.nodes.length,147);
assert.equal(Object.keys(targets.targets).length,105);
assert.equal(catalog.schema,'wh40k-army-roster-catalog/v1');
assert.equal(catalog.units.length,50);
assert.equal(catalog.detachments.length,10);
assert.equal(catalog.detachmentRules.length,10);
assert.equal(catalog.enhancements.length,34);
for(const unit of datasheets.datasheets)assert.ok(targets.targets[unit.id],`missing Datasheet target: ${unit.id}`);
for(const detachment of detachments)assert.ok(targets.targets[`detachment-${detachment.id}`],`missing Detachment target: ${detachment.id}`);
for(const id of ['army-rule-shadow-in-the-warp','army-rule-synapse','unit-broodlord','unit-hive-tyrant','unit-neurotyrant','unit-norn-emissary'])assert.ok(targets.targets[id],`missing canonical target: ${id}`);
for(const text of ['Shadow in the Warp','Synapse','Vicious Insight','Node Lash','Adaptive Biology','Elevated Might','Mindhunger'])assert.ok(targets.html.includes(text),`missing target-data content: ${text}`);
assert.equal(new Set(catalog.detachmentRules.map(rule=>rule.id)).size,10);
assert.equal(new Set(catalog.enhancements.map(rule=>rule.id)).size,34);
assert.equal(catalog.units.reduce((sum,unit)=>sum+unit.gameSelections.wargearAbilities.length,0),0);
console.log('Tyranids Army Book target-data QA passed: 50 Datasheets, 10 Detachments, 34 Enhancements, 51 Stratagems.');
