import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.dirname(fileURLToPath(import.meta.url)),bookRoot=path.resolve(root,'..');
const reader=fs.readFileSync(path.join(bookRoot,'reader.html'),'utf8'),config=JSON.parse(fs.readFileSync(path.join(bookRoot,'book.config.json'),'utf8')),manifest=JSON.parse(fs.readFileSync(path.join(bookRoot,'sources/source-manifest.json'),'utf8')),app=fs.readFileSync(path.join(bookRoot,'scripts/app.js'),'utf8'),related=fs.readFileSync(path.join(root,'related-rules.inc'),'utf8');
function extract(tag,id,html=reader){const opener=new RegExp(`<${tag}\\b[^>]*\\bid="${id}"[^>]*>`,'i').exec(html);assert.ok(opener,`Missing ${tag}#${id}`);const tags=new RegExp(`<\\/?${tag}\\b[^>]*>`,'gi');tags.lastIndex=opener.index;let depth=0;for(let match;(match=tags.exec(html));){depth+=match[0][1]==='/'?-1:1;if(depth===0)return html.slice(opener.index,tags.lastIndex);}assert.fail(`Unclosed ${tag}#${id}`);}
const routeIds=[...reader.matchAll(/<(?:section|article)[^>]+id="((?:detachment|unit)-[^"]+)"/g)].map(match=>match[1]),detachments=routeIds.filter(id=>id.startsWith('detachment-')),units=routeIds.filter(id=>id.startsWith('unit-')),routes=['index.html','army-rules.html','updates.html',...routeIds.map(id=>id.replace(/^(?:detachment|unit)-/,'')+'.html')],htmlFiles=fs.readdirSync(root).filter(file=>file.endsWith('.html')).sort();
assert.equal(detachments.length,24);assert.equal(units.length,98);assert.equal((reader.match(/Space Marines shared datasheet/g)||[]).length,82);assert.equal(routes.length,125);assert.deepEqual(htmlFiles,routes.slice().sort());
for(const route of routes){const html=fs.readFileSync(path.join(root,route),'utf8'),target=route==='index.html'?'start':route==='army-rules.html'?'army-rules':route==='updates.html'?'updates':detachments.includes(`detachment-${route.slice(0,-5)}`)?`detachment-${route.slice(0,-5)}`:`unit-${route.slice(0,-5)}`;assert.match(html,/data-canonical-reader="\.\.\/reader\.html"/);assert.match(html,new RegExp(`data-canonical-target="${target}"`));assert.match(html,/\.\.\/\.\.\/shared\/mobile-route-redirect\.js\?v=1/);assert.doesNotMatch(html,/<(?:article|section)\b|class="[^"]*\bunit-card\b|data-rule-id=/);}
const start=extract('section','start'),belial=extract('article','unit-belial'),knights=extract('article','unit-deathwing-knights');assert.match(reader,/\.\/scripts\/app\.js\?v=7/);assert.match(reader,/\.\.\/shared\/book-roster-enhancements\.js\?v=\d+/);assert.match(app,/relatedRules:\{enabled:true\}/);assert.match(start,/Source-limited preview/);assert.match(start,/faction-hero-cover/);assert.doesNotMatch(belial,/dark-angels-cover/);assert.match(extract('section','army-rules'),/data-term="space-marines-army-rule-oath-of-moment"/);assert.equal((reader.match(/Codex source required/g)||[]).length,3);
for(const file of ['hellblaster-squad.html','intercessor-squad.html','bladeguard-veteran-squad.html','terminator-squad.html','terminator-assault-squad.html','outrider-squad.html','land-raider.html','redemptor-dreadnought.html'])assert.ok(htmlFiles.includes(file));for(const file of ['victrix-honour-guard.html','roboute-guilliman.html','marneus-calgar-in-armour-of-antilochus.html','vulkan-hestan.html','kayvaan-shrike.html','ravenwing-talonmaster.html','deathwing-strikemaster.html','deathwing-command-squad.html'])assert.ok(!htmlFiles.includes(file));
for(const [leader,target] of [['belial','unit-terminator-squad'],['azrael','unit-hellblaster-squad'],['sammael','unit-outrider-squad']])assert.match(extract('article',`unit-${leader}`),new RegExp(`data-journey-target="${target}"`));assert.match(knights,/Watcher in the Dark/);assert.match(knights,/These abilities apply only while the corresponding wargear is equipped\./);assert.match(extract('article','unit-hellblaster-squad'),/data-term="space-marines-/);assert.doesNotMatch(extract('article','unit-hellblaster-squad'),/data-term="dark-angels-weapon-/);
assert.equal(config.generatedMobile,true);assert.equal(manifest.gates.publishAsComplete,false);assert.match(related,/class="stratagem surface"/);assert.match(reader,/\.\.\/shared\/army-related-rules\.js\?v=\d+/);assert.ok(!fs.existsSync(path.join(root,'mobile.js'))&&!fs.existsSync(path.join(root,'mobile.css'))&&!fs.existsSync(path.join(root,'phone-popup-controller.js')));
console.log('Dark Angels responsive QA: 125 content-free routes, 24 Detachments, 16 local and 82 shared Datasheets.');
